// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.errors

/** Base type for every exception thrown by the DemoApiScalarGalaxy SDK. */
open class DemoApiScalarGalaxyException(message: String? = null, cause: Throwable? = null) :
    RuntimeException(message, cause)
