// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.errors

class DemoApiScalarGalaxyIoException(message: String? = null, cause: Throwable? = null) :
    DemoApiScalarGalaxyException(message, cause)
