// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.errors

import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.http.Headers

/**
 * Base type for HTTP failures raised by the DemoApiScalarGalaxy SDK.
 *
 * Subclasses describe a specific HTTP status code (4xx/5xx); each carries the parsed status,
 * response headers, and raw response body so callers can inspect server-side error payloads without
 * losing fidelity.
 */
abstract class DemoApiScalarGalaxyServiceException
protected constructor(message: String, cause: Throwable? = null) :
    DemoApiScalarGalaxyException(message, cause) {

    abstract fun statusCode(): Int

    abstract fun headers(): Headers

    abstract fun body(): JsonValue
}
