// File generated by Scalar SDK Generator. DO NOT EDIT.

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `./gradlew test`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
import com.demoapiscalargalaxy.api.client.DemoApiScalarGalaxyClient
import com.demoapiscalargalaxy.api.client.okhttp.DemoApiScalarGalaxyOkHttpClient
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateTokenParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateUserParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationListMeParams
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBody
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBodyCreateParams
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.PlanetCreateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetDeleteParams
import com.demoapiscalargalaxy.api.models.planets.PlanetListParams
import com.demoapiscalargalaxy.api.models.planets.PlanetRetrieveParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUpdateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUploadImageParams
import java.nio.file.Files
import java.nio.file.Path
import java.time.Duration
import kotlin.test.Test

private val client: DemoApiScalarGalaxyClient =
    DemoApiScalarGalaxyOkHttpClient.builder()
        .fromEnv()
        .maxRetries(0)
        .timeout(Duration.ofSeconds(30))
        .build()

private data class SmokeResult(
    val operation: String,
    val method: String,
    val path: String,
    val label: String? = null,
    val status: String,
    val durationMs: Long,
    val error: String? = null,
)

// `label` says which of an operation's two calls this is — "required params" or "all params".
// It stays null when the operation contributed a single case.
private data class SmokeCase(
    val operation: String,
    val method: String,
    val path: String,
    val run: () -> Unit,
    val label: String? = null,
)

private fun _smokeCase0() {
    val params = PlanetListParams.builder().limit(10L).offset(0L).build()
    val planet = client.planets().list(params)
}

private fun _smokeCase1() {
    val params =
        PlanetCreateParams.builder()
            .planet(Planet.builder().name("Mars").type(Planet.Type.of("terrestrial")).build())
            .build()
    val planet = client.planets().create(params)
}

private fun _smokeCase2() {
    val params = PlanetRetrieveParams.builder().planetId(1L).build()
    val planet = client.planets().retrieve(params)
}

private fun _smokeCase3() {
    val params =
        PlanetUpdateParams.builder()
            .planetId(1L)
            .planet(Planet.builder().name("Mars").type(Planet.Type.of("terrestrial")).build())
            .build()
    val planet = client.planets().update(params)
}

private fun _smokeCase4() {
    val params = PlanetDeleteParams.builder().planetId(1L).build()

    client.planets().delete(params)
}

private fun _smokeCase5() {
    val params = PlanetUploadImageParams.builder().planetId(1L).build()
    val planet = client.planets().uploadImage(params)
}

private fun _smokeCase6() {
    val params =
        PlanetUploadImageParams.builder()
            .planetId(1L)
            .image(java.io.ByteArrayInputStream(ByteArray(0)))
            .build()
    val planet = client.planets().uploadImage(params)
}

private fun _smokeCase7() {
    val params =
        CelestialBodyCreateParams.builder()
            .celestialBody(
                CelestialBody.ofPlanet(
                    Planet.builder().name("Mars").type(Planet.Type.of("terrestrial")).build()
                )
            )
            .build()
    val celestialBody = client.celestialBodies().create(params)
}

private fun _smokeCase8() {
    val params =
        AuthenticationCreateUserParams.builder()
            .name("Marc")
            .email("marc@scalar.com")
            .password("i-love-scalar")
            .build()
    val authentication = client.authentication().createUser(params)
}

private fun _smokeCase9() {
    val params =
        AuthenticationCreateTokenParams.builder()
            .email("marc@scalar.com")
            .password("i-love-scalar")
            .build()
    val authentication = client.authentication().createToken(params)
}

private fun _smokeCase10() {
    val authentication = client.authentication().listMe(AuthenticationListMeParams.none())
}

private val cases =
    listOf(
        SmokeCase(
            operation = "list",
            method = "GET",
            path = "/planets",
            run = ::_smokeCase0,
        ),
        SmokeCase(
            operation = "create",
            method = "POST",
            path = "/planets",
            run = ::_smokeCase1,
        ),
        SmokeCase(
            operation = "retrieve",
            method = "GET",
            path = "/planets/{planetId}",
            run = ::_smokeCase2,
        ),
        SmokeCase(
            operation = "update",
            method = "PUT",
            path = "/planets/{planetId}",
            run = ::_smokeCase3,
        ),
        SmokeCase(
            operation = "delete",
            method = "DELETE",
            path = "/planets/{planetId}",
            run = ::_smokeCase4,
        ),
        SmokeCase(
            operation = "uploadImage",
            method = "POST",
            path = "/planets/{planetId}/image",
            label = "required params",
            run = ::_smokeCase5,
        ),
        SmokeCase(
            operation = "uploadImage",
            method = "POST",
            path = "/planets/{planetId}/image",
            label = "all params",
            run = ::_smokeCase6,
        ),
        SmokeCase(
            operation = "create",
            method = "POST",
            path = "/celestial-bodies",
            run = ::_smokeCase7,
        ),
        SmokeCase(
            operation = "createUser",
            method = "POST",
            path = "/user/signup",
            run = ::_smokeCase8,
        ),
        SmokeCase(
            operation = "createToken",
            method = "POST",
            path = "/auth/token",
            run = ::_smokeCase9,
        ),
        SmokeCase(
            operation = "listMe",
            method = "GET",
            path = "/me",
            run = ::_smokeCase10,
        ),
    )

private fun selectedCases(): List<SmokeCase> {
    val filter = System.getenv("SCALAR_SMOKE_FILTER")
    val needles = filter?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }.orEmpty()
    if (needles.isEmpty()) return cases
    return cases.filter { testCase ->
        needles.any { needle ->
            testCase.operation.contains(needle) || testCase.path.contains(needle)
        }
    }
}

private fun runCase(testCase: SmokeCase): SmokeResult {
    val startedAt = System.nanoTime()
    return try {
        testCase.run()
        SmokeResult(
            operation = testCase.operation,
            method = testCase.method,
            path = testCase.path,
            label = testCase.label,
            status = "passed",
            durationMs = (System.nanoTime() - startedAt) / 1_000_000,
        )
    } catch (error: Throwable) {
        SmokeResult(
            operation = testCase.operation,
            method = testCase.method,
            path = testCase.path,
            label = testCase.label,
            status = "failed",
            durationMs = (System.nanoTime() - startedAt) / 1_000_000,
            error = error.stackTraceToString(),
        )
    }
}

private fun writeReport(results: List<SmokeResult>, failed: Int) {
    val reportPath = System.getenv("SCALAR_SMOKE_REPORT")
    val json = buildString {
        append("{\"total\":").append(results.size)
        append(",\"failed\":").append(failed)
        append(",\"results\":[")
        results.forEachIndexed { index, result ->
            if (index > 0) append(",")
            append("{\"operation\":\"").append(escapeJson(result.operation)).append("\",")
            append("\"method\":\"").append(escapeJson(result.method)).append("\",")
            append("\"path\":\"").append(escapeJson(result.path)).append("\",")
            result.label?.let { append("\"label\":\"").append(escapeJson(it)).append("\",") }
            append("\"status\":\"").append(escapeJson(result.status)).append("\",")
            append("\"durationMs\":").append(result.durationMs)
            result.error?.let { append(",\"error\":\"").append(escapeJson(it)).append("\"") }
            append("}")
        }
        append("]}")
    }
    if (!reportPath.isNullOrBlank()) Files.writeString(Path.of(reportPath), json)
}

private fun escapeJson(value: String): String = buildString {
    for (char in value) {
        when (char) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(char)
        }
    }
}

class SmokeTest {
    @Test
    fun smoke() {
        val selected = selectedCases()
        val results = selected.map(::runCase)
        val failed = results.count { it.status == "failed" }
        writeReport(results, failed)

        for (result in results) {
            val suffix = result.label?.let { " [" + it + "]" }.orEmpty()
            if (result.status == "passed") {
                println(
                    "PASS ${result.operation}$suffix (${result.method} ${result.path}) ${result.durationMs}ms"
                )
            } else {
                System.err.println(
                    "FAIL ${result.operation}$suffix (${result.method} ${result.path})\n${result.error.orEmpty()}"
                )
            }
        }

        if (failed > 0 || results.isEmpty()) {
            throw AssertionError("${results.size - failed}/${results.size} samples passed")
        }
    }
}
