// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.client

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.getPackageVersion
import com.demoapiscalargalaxy.api.services.async.AuthenticationServiceAsync
import com.demoapiscalargalaxy.api.services.async.AuthenticationServiceAsyncImpl
import com.demoapiscalargalaxy.api.services.async.CelestialBodyServiceAsync
import com.demoapiscalargalaxy.api.services.async.CelestialBodyServiceAsyncImpl
import com.demoapiscalargalaxy.api.services.async.PlanetServiceAsync
import com.demoapiscalargalaxy.api.services.async.PlanetServiceAsyncImpl
import com.demoapiscalargalaxy.api.services.async.WebhookServiceAsync
import com.demoapiscalargalaxy.api.services.async.WebhookServiceAsyncImpl

class DemoApiScalarGalaxyClientAsyncImpl(private val clientOptions: ClientOptions) :
    DemoApiScalarGalaxyClientAsync {

    private val clientOptionsWithUserAgent =
        if (clientOptions.headers.names().contains("User-Agent")) clientOptions
        else
            clientOptions
                .toBuilder()
                .putHeader("User-Agent", "${javaClass.simpleName}/Kotlin ${getPackageVersion()}")
                .build()

    // Pass the original clientOptions so that this client sets its own User-Agent.
    private val sync: DemoApiScalarGalaxyClient by lazy {
        DemoApiScalarGalaxyClientImpl(clientOptions)
    }

    private val withRawResponse: DemoApiScalarGalaxyClientAsync.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    private val planets: PlanetServiceAsync by lazy {
        PlanetServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val celestialBodies: CelestialBodyServiceAsync by lazy {
        CelestialBodyServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val authentication: AuthenticationServiceAsync by lazy {
        AuthenticationServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    private val webhooks: WebhookServiceAsync by lazy {
        WebhookServiceAsyncImpl(clientOptionsWithUserAgent)
    }

    override fun sync(): DemoApiScalarGalaxyClient = sync

    override fun withRawResponse(): DemoApiScalarGalaxyClientAsync.WithRawResponse = withRawResponse

    override fun withOptions(
        modifier: (ClientOptions.Builder) -> Unit
    ): DemoApiScalarGalaxyClientAsync =
        DemoApiScalarGalaxyClientAsyncImpl(clientOptions.toBuilder().apply(modifier).build())

    /** Everything about planets */
    override fun planets(): PlanetServiceAsync = planets

    /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
    override fun celestialBodies(): CelestialBodyServiceAsync = celestialBodies

    /**
     * Some endpoints are public, but some require authentication. We provide all the required
     * endpoints to create an account and authorize yourself.
     */
    override fun authentication(): AuthenticationServiceAsync = authentication

    override fun webhooks(): WebhookServiceAsync = webhooks

    override fun close() = clientOptions.close()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        DemoApiScalarGalaxyClientAsync.WithRawResponse {

        private val planets: PlanetServiceAsync.WithRawResponse by lazy {
            PlanetServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val celestialBodies: CelestialBodyServiceAsync.WithRawResponse by lazy {
            CelestialBodyServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val authentication: AuthenticationServiceAsync.WithRawResponse by lazy {
            AuthenticationServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        private val webhooks: WebhookServiceAsync.WithRawResponse by lazy {
            WebhookServiceAsyncImpl.WithRawResponseImpl(clientOptions)
        }

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): DemoApiScalarGalaxyClientAsync.WithRawResponse =
            DemoApiScalarGalaxyClientAsyncImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )

        /** Everything about planets */
        override fun planets(): PlanetServiceAsync.WithRawResponse = planets

        /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
        override fun celestialBodies(): CelestialBodyServiceAsync.WithRawResponse = celestialBodies

        /**
         * Some endpoints are public, but some require authentication. We provide all the required
         * endpoints to create an account and authorize yourself.
         */
        override fun authentication(): AuthenticationServiceAsync.WithRawResponse = authentication

        override fun webhooks(): WebhookServiceAsync.WithRawResponse = webhooks
    }
}
