// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.client

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.services.async.AuthenticationServiceAsync
import com.demoapiscalargalaxy.api.services.async.CelestialBodyServiceAsync
import com.demoapiscalargalaxy.api.services.async.PlanetServiceAsync
import com.demoapiscalargalaxy.api.services.async.WebhookServiceAsync

/**
 * A client for interacting with the Demo API (Scalar Galaxy) asynchronously. You can also switch to
 * synchronous execution via the [sync] method.
 *
 * This client performs best when you create a single instance and reuse it for all interactions
 * with the REST API. This is because each client holds its own connection pool and thread pools.
 * Reusing connections and threads reduces latency and saves memory. The client also handles rate
 * limiting per client. This means that creating and using multiple instances at the same time will
 * not respect rate limits.
 *
 * The threads and connections that are held will be released automatically if they remain idle. But
 * if you are writing an application that needs to aggressively release unused resources, then you
 * may call [close].
 */
interface DemoApiScalarGalaxyClientAsync {

    /**
     * Returns a version of this client that uses synchronous execution.
     *
     * The returned client shares its resources, like its connection pool and thread pools, with
     * this client.
     */
    fun sync(): DemoApiScalarGalaxyClient

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: (ClientOptions.Builder) -> Unit): DemoApiScalarGalaxyClientAsync

    /** Everything about planets */
    fun planets(): PlanetServiceAsync

    /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
    fun celestialBodies(): CelestialBodyServiceAsync

    /**
     * Some endpoints are public, but some require authentication. We provide all the required
     * endpoints to create an account and authorize yourself.
     */
    fun authentication(): AuthenticationServiceAsync

    fun webhooks(): WebhookServiceAsync

    /**
     * Closes this client, relinquishing any underlying resources.
     *
     * This is purposefully not inherited from [AutoCloseable] because the client is long-lived and
     * usually should not be synchronously closed via try-with-resources.
     *
     * It's also usually not necessary to call this method at all. the default HTTP client
     * automatically releases threads and connections if they remain idle, but if you are writing an
     * application that needs to aggressively release unused resources, then you may call this
     * method.
     */
    fun close()

    /**
     * A view of [DemoApiScalarGalaxyClientAsync] that provides access to raw HTTP responses for
     * each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): DemoApiScalarGalaxyClientAsync.WithRawResponse

        /** Everything about planets */
        fun planets(): PlanetServiceAsync.WithRawResponse

        /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
        fun celestialBodies(): CelestialBodyServiceAsync.WithRawResponse

        /**
         * Some endpoints are public, but some require authentication. We provide all the required
         * endpoints to create an account and authorize yourself.
         */
        fun authentication(): AuthenticationServiceAsync.WithRawResponse

        fun webhooks(): WebhookServiceAsync.WithRawResponse
    }
}
