// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.client

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.getPackageVersion
import com.demoapiscalargalaxy.api.services.blocking.AuthenticationService
import com.demoapiscalargalaxy.api.services.blocking.AuthenticationServiceImpl
import com.demoapiscalargalaxy.api.services.blocking.CelestialBodyService
import com.demoapiscalargalaxy.api.services.blocking.CelestialBodyServiceImpl
import com.demoapiscalargalaxy.api.services.blocking.PlanetService
import com.demoapiscalargalaxy.api.services.blocking.PlanetServiceImpl
import com.demoapiscalargalaxy.api.services.blocking.WebhookService
import com.demoapiscalargalaxy.api.services.blocking.WebhookServiceImpl

class DemoApiScalarGalaxyClientImpl(private val clientOptions: ClientOptions) :
    DemoApiScalarGalaxyClient {

    private val clientOptionsWithUserAgent =
        if (clientOptions.headers.names().contains("User-Agent")) clientOptions
        else
            clientOptions
                .toBuilder()
                .putHeader("User-Agent", "${javaClass.simpleName}/Kotlin ${getPackageVersion()}")
                .build()

    // Pass the original clientOptions so that this client sets its own User-Agent.
    private val async: DemoApiScalarGalaxyClientAsync by lazy {
        DemoApiScalarGalaxyClientAsyncImpl(clientOptions)
    }

    private val withRawResponse: DemoApiScalarGalaxyClient.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    private val planets: PlanetService by lazy { PlanetServiceImpl(clientOptionsWithUserAgent) }

    private val celestialBodies: CelestialBodyService by lazy {
        CelestialBodyServiceImpl(clientOptionsWithUserAgent)
    }

    private val authentication: AuthenticationService by lazy {
        AuthenticationServiceImpl(clientOptionsWithUserAgent)
    }

    private val webhooks: WebhookService by lazy { WebhookServiceImpl(clientOptionsWithUserAgent) }

    override fun async(): DemoApiScalarGalaxyClientAsync = async

    override fun withRawResponse(): DemoApiScalarGalaxyClient.WithRawResponse = withRawResponse

    override fun withOptions(modifier: (ClientOptions.Builder) -> Unit): DemoApiScalarGalaxyClient =
        DemoApiScalarGalaxyClientImpl(clientOptions.toBuilder().apply(modifier).build())

    /** Everything about planets */
    override fun planets(): PlanetService = planets

    /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
    override fun celestialBodies(): CelestialBodyService = celestialBodies

    /**
     * Some endpoints are public, but some require authentication. We provide all the required
     * endpoints to create an account and authorize yourself.
     */
    override fun authentication(): AuthenticationService = authentication

    override fun webhooks(): WebhookService = webhooks

    override fun close() = clientOptions.close()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        DemoApiScalarGalaxyClient.WithRawResponse {

        private val planets: PlanetService.WithRawResponse by lazy {
            PlanetServiceImpl.WithRawResponseImpl(clientOptions)
        }

        private val celestialBodies: CelestialBodyService.WithRawResponse by lazy {
            CelestialBodyServiceImpl.WithRawResponseImpl(clientOptions)
        }

        private val authentication: AuthenticationService.WithRawResponse by lazy {
            AuthenticationServiceImpl.WithRawResponseImpl(clientOptions)
        }

        private val webhooks: WebhookService.WithRawResponse by lazy {
            WebhookServiceImpl.WithRawResponseImpl(clientOptions)
        }

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): DemoApiScalarGalaxyClient.WithRawResponse =
            DemoApiScalarGalaxyClientImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )

        /** Everything about planets */
        override fun planets(): PlanetService.WithRawResponse = planets

        /** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
        override fun celestialBodies(): CelestialBodyService.WithRawResponse = celestialBodies

        /**
         * Some endpoints are public, but some require authentication. We provide all the required
         * endpoints to create an account and authorize yourself.
         */
        override fun authentication(): AuthenticationService.WithRawResponse = authentication

        override fun webhooks(): WebhookService.WithRawResponse = webhooks
    }
}
