// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.async

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.core.handlers.emptyHandler
import com.demoapiscalargalaxy.api.core.handlers.errorBodyHandler
import com.demoapiscalargalaxy.api.core.handlers.errorHandler
import com.demoapiscalargalaxy.api.core.handlers.jsonHandler
import com.demoapiscalargalaxy.api.core.http.HttpMethod
import com.demoapiscalargalaxy.api.core.http.HttpRequest
import com.demoapiscalargalaxy.api.core.http.HttpResponse
import com.demoapiscalargalaxy.api.core.http.HttpResponse.Handler
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.core.http.json
import com.demoapiscalargalaxy.api.core.http.multipartFormData
import com.demoapiscalargalaxy.api.core.http.parseable
import com.demoapiscalargalaxy.api.core.prepareAsync
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.PlanetCreateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetDeleteParams
import com.demoapiscalargalaxy.api.models.planets.PlanetListParams
import com.demoapiscalargalaxy.api.models.planets.PlanetListResponse
import com.demoapiscalargalaxy.api.models.planets.PlanetRetrieveParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUpdateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUploadImageParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUploadImageResponse

/** Everything about planets */
class PlanetServiceAsyncImpl internal constructor(private val clientOptions: ClientOptions) :
    PlanetServiceAsync {

    private val withRawResponse: PlanetServiceAsync.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): PlanetServiceAsync.WithRawResponse = withRawResponse

    override fun withOptions(modifier: (ClientOptions.Builder) -> Unit): PlanetServiceAsync =
        PlanetServiceAsyncImpl(clientOptions.toBuilder().apply(modifier).build())

    override suspend fun create(
        params: PlanetCreateParams,
        requestOptions: RequestOptions,
    ): Planet =
        // post /planets
        withRawResponse().create(params, requestOptions).parse()

    override suspend fun retrieve(
        params: PlanetRetrieveParams,
        requestOptions: RequestOptions,
    ): Planet =
        // get /planets/{planetId}
        withRawResponse().retrieve(params, requestOptions).parse()

    override suspend fun update(
        params: PlanetUpdateParams,
        requestOptions: RequestOptions,
    ): Planet =
        // put /planets/{planetId}
        withRawResponse().update(params, requestOptions).parse()

    override suspend fun list(
        params: PlanetListParams,
        requestOptions: RequestOptions,
    ): PlanetListResponse =
        // get /planets
        withRawResponse().list(params, requestOptions).parse()

    override suspend fun delete(params: PlanetDeleteParams, requestOptions: RequestOptions) {
        // delete /planets/{planetId}
        withRawResponse().delete(params, requestOptions)
    }

    override suspend fun uploadImage(
        params: PlanetUploadImageParams,
        requestOptions: RequestOptions,
    ): PlanetUploadImageResponse =
        // post /planets/{planetId}/image
        withRawResponse().uploadImage(params, requestOptions).parse()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        PlanetServiceAsync.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): PlanetServiceAsync.WithRawResponse =
            PlanetServiceAsyncImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )

        private val createHandler: Handler<Planet> = jsonHandler<Planet>(clientOptions.jsonMapper)

        override suspend fun create(
            params: PlanetCreateParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Planet> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { createHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val retrieveHandler: Handler<Planet> = jsonHandler<Planet>(clientOptions.jsonMapper)

        override suspend fun retrieve(
            params: PlanetRetrieveParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Planet> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("planetId", params.planetId())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets", params._pathParam(0))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { retrieveHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val updateHandler: Handler<Planet> = jsonHandler<Planet>(clientOptions.jsonMapper)

        override suspend fun update(
            params: PlanetUpdateParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Planet> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("planetId", params.planetId())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.PUT)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets", params._pathParam(0))
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { updateHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val listHandler: Handler<PlanetListResponse> =
            jsonHandler<PlanetListResponse>(clientOptions.jsonMapper)

        override suspend fun list(
            params: PlanetListParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<PlanetListResponse> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets")
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { listHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val deleteHandler: Handler<Void?> = emptyHandler()

        override suspend fun delete(
            params: PlanetDeleteParams,
            requestOptions: RequestOptions,
        ): HttpResponse {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("planetId", params.planetId())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.DELETE)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets", params._pathParam(0))
                    .apply { params._body()?.let { body(json(clientOptions.jsonMapper, it)) } }
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response.use { deleteHandler.handle(it) }
            }
        }

        private val uploadImageHandler: Handler<PlanetUploadImageResponse> =
            jsonHandler<PlanetUploadImageResponse>(clientOptions.jsonMapper)

        override suspend fun uploadImage(
            params: PlanetUploadImageParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<PlanetUploadImageResponse> {
            // We check here instead of in the params builder because this can be specified
            // positionally or in the params class.
            checkRequired("planetId", params.planetId())
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("planets", params._pathParam(0), "image")
                    .body(multipartFormData(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepareAsync(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.executeAsync(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { uploadImageHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }
    }
}
