// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateTokenParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateUserParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationListMeParams
import com.demoapiscalargalaxy.api.models.authentication.Token
import com.demoapiscalargalaxy.api.models.authentication.User
import com.google.errorprone.annotations.MustBeClosed

/**
 * Some endpoints are public, but some require authentication. We provide all the required endpoints
 * to create an account and authorize yourself.
 */
interface AuthenticationService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: (ClientOptions.Builder) -> Unit): AuthenticationService

    /** Yeah, this is the boring security stuff. Just get your super secret token and move on. */
    fun createToken(
        params: AuthenticationCreateTokenParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Token

    /** Time to create a user account, eh? */
    fun createUser(
        params: AuthenticationCreateUserParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): User

    /** Find yourself they say. That's what you can do here. */
    fun listMe(
        params: AuthenticationListMeParams = AuthenticationListMeParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): User

    /** @see listMe */
    fun listMe(requestOptions: RequestOptions): User =
        listMe(AuthenticationListMeParams.none(), requestOptions)

    /**
     * A view of [AuthenticationService] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): AuthenticationService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /auth/token`, but is otherwise the same as
         * [AuthenticationService.createToken].
         */
        @MustBeClosed
        fun createToken(
            params: AuthenticationCreateTokenParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Token>

        /**
         * Returns a raw HTTP response for `post /user/signup`, but is otherwise the same as
         * [AuthenticationService.createUser].
         */
        @MustBeClosed
        fun createUser(
            params: AuthenticationCreateUserParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<User>

        /**
         * Returns a raw HTTP response for `get /me`, but is otherwise the same as
         * [AuthenticationService.listMe].
         */
        @MustBeClosed
        fun listMe(
            params: AuthenticationListMeParams = AuthenticationListMeParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<User>

        /** @see listMe */
        @MustBeClosed
        fun listMe(requestOptions: RequestOptions): HttpResponseFor<User> =
            listMe(AuthenticationListMeParams.none(), requestOptions)
    }
}
