// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.handlers.errorBodyHandler
import com.demoapiscalargalaxy.api.core.handlers.errorHandler
import com.demoapiscalargalaxy.api.core.handlers.jsonHandler
import com.demoapiscalargalaxy.api.core.http.HttpMethod
import com.demoapiscalargalaxy.api.core.http.HttpRequest
import com.demoapiscalargalaxy.api.core.http.HttpResponse
import com.demoapiscalargalaxy.api.core.http.HttpResponse.Handler
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.core.http.json
import com.demoapiscalargalaxy.api.core.http.parseable
import com.demoapiscalargalaxy.api.core.prepare
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateTokenParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationCreateUserParams
import com.demoapiscalargalaxy.api.models.authentication.AuthenticationListMeParams
import com.demoapiscalargalaxy.api.models.authentication.Token
import com.demoapiscalargalaxy.api.models.authentication.User

/**
 * Some endpoints are public, but some require authentication. We provide all the required endpoints
 * to create an account and authorize yourself.
 */
class AuthenticationServiceImpl internal constructor(private val clientOptions: ClientOptions) :
    AuthenticationService {

    private val withRawResponse: AuthenticationService.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): AuthenticationService.WithRawResponse = withRawResponse

    override fun withOptions(modifier: (ClientOptions.Builder) -> Unit): AuthenticationService =
        AuthenticationServiceImpl(clientOptions.toBuilder().apply(modifier).build())

    override fun createToken(
        params: AuthenticationCreateTokenParams,
        requestOptions: RequestOptions,
    ): Token =
        // post /auth/token
        withRawResponse().createToken(params, requestOptions).parse()

    override fun createUser(
        params: AuthenticationCreateUserParams,
        requestOptions: RequestOptions,
    ): User =
        // post /user/signup
        withRawResponse().createUser(params, requestOptions).parse()

    override fun listMe(params: AuthenticationListMeParams, requestOptions: RequestOptions): User =
        // get /me
        withRawResponse().listMe(params, requestOptions).parse()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        AuthenticationService.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): AuthenticationService.WithRawResponse =
            AuthenticationServiceImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )

        private val createTokenHandler: Handler<Token> =
            jsonHandler<Token>(clientOptions.jsonMapper)

        override fun createToken(
            params: AuthenticationCreateTokenParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<Token> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("auth", "token")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { createTokenHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val createUserHandler: Handler<User> = jsonHandler<User>(clientOptions.jsonMapper)

        override fun createUser(
            params: AuthenticationCreateUserParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<User> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("user", "signup")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { createUserHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }

        private val listMeHandler: Handler<User> = jsonHandler<User>(clientOptions.jsonMapper)

        override fun listMe(
            params: AuthenticationListMeParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<User> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.GET)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("me")
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { listMeHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }
    }
}
