// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBody
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBodyCreateParams
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.Satellite
import com.google.errorprone.annotations.MustBeClosed

/** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
interface CelestialBodyService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: (ClientOptions.Builder) -> Unit): CelestialBodyService

    /** Create a celestial body */
    fun create(
        params: CelestialBodyCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CelestialBody

    /** @see create */
    fun create(
        celestialBody: CelestialBody,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CelestialBody =
        create(
            CelestialBodyCreateParams.builder().celestialBody(celestialBody).build(),
            requestOptions,
        )

    /** @see create */
    fun create(
        planet: Planet,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CelestialBody = create(CelestialBody.ofPlanet(planet), requestOptions)

    /** @see create */
    fun create(
        satellite: Satellite,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CelestialBody = create(CelestialBody.ofSatellite(satellite), requestOptions)

    /**
     * A view of [CelestialBodyService] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): CelestialBodyService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /celestial-bodies`, but is otherwise the same as
         * [CelestialBodyService.create].
         */
        @MustBeClosed
        fun create(
            params: CelestialBodyCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<CelestialBody>

        /** @see create */
        @MustBeClosed
        fun create(
            celestialBody: CelestialBody,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<CelestialBody> =
            create(
                CelestialBodyCreateParams.builder().celestialBody(celestialBody).build(),
                requestOptions,
            )

        /** @see create */
        @MustBeClosed
        fun create(
            planet: Planet,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<CelestialBody> = create(CelestialBody.ofPlanet(planet), requestOptions)

        /** @see create */
        @MustBeClosed
        fun create(
            satellite: Satellite,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<CelestialBody> =
            create(CelestialBody.ofSatellite(satellite), requestOptions)
    }
}
