// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.handlers.errorBodyHandler
import com.demoapiscalargalaxy.api.core.handlers.errorHandler
import com.demoapiscalargalaxy.api.core.handlers.jsonHandler
import com.demoapiscalargalaxy.api.core.http.HttpMethod
import com.demoapiscalargalaxy.api.core.http.HttpRequest
import com.demoapiscalargalaxy.api.core.http.HttpResponse
import com.demoapiscalargalaxy.api.core.http.HttpResponse.Handler
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.core.http.json
import com.demoapiscalargalaxy.api.core.http.parseable
import com.demoapiscalargalaxy.api.core.prepare
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBody
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBodyCreateParams

/** Celestial bodies are the planets and satellites in the Scalar Galaxy. */
class CelestialBodyServiceImpl internal constructor(private val clientOptions: ClientOptions) :
    CelestialBodyService {

    private val withRawResponse: CelestialBodyService.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): CelestialBodyService.WithRawResponse = withRawResponse

    override fun withOptions(modifier: (ClientOptions.Builder) -> Unit): CelestialBodyService =
        CelestialBodyServiceImpl(clientOptions.toBuilder().apply(modifier).build())

    override fun create(
        params: CelestialBodyCreateParams,
        requestOptions: RequestOptions,
    ): CelestialBody =
        // post /celestial-bodies
        withRawResponse().create(params, requestOptions).parse()

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        CelestialBodyService.WithRawResponse {

        private val errorHandler: Handler<HttpResponse> =
            errorHandler(errorBodyHandler(clientOptions.jsonMapper))

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): CelestialBodyService.WithRawResponse =
            CelestialBodyServiceImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )

        private val createHandler: Handler<CelestialBody> =
            jsonHandler<CelestialBody>(clientOptions.jsonMapper)

        override fun create(
            params: CelestialBodyCreateParams,
            requestOptions: RequestOptions,
        ): HttpResponseFor<CelestialBody> {
            val request =
                HttpRequest.builder()
                    .method(HttpMethod.POST)
                    .baseUrl(clientOptions.baseUrl())
                    .addPathSegments("celestial-bodies")
                    .body(json(clientOptions.jsonMapper, params._body()))
                    .build()
                    .prepare(clientOptions, params)
            val requestOptions = requestOptions.applyDefaults(RequestOptions.from(clientOptions))
            val response = clientOptions.httpClient.execute(request, requestOptions)
            return errorHandler.handle(response).parseable {
                response
                    .use { createHandler.handle(it) }
                    .also {
                        if (requestOptions.responseValidation!!) {
                            it.validate()
                        }
                    }
            }
        }
    }
}
