// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.RequestOptions
import com.demoapiscalargalaxy.api.core.http.HttpResponse
import com.demoapiscalargalaxy.api.core.http.HttpResponseFor
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.PlanetCreateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetDeleteParams
import com.demoapiscalargalaxy.api.models.planets.PlanetListParams
import com.demoapiscalargalaxy.api.models.planets.PlanetListResponse
import com.demoapiscalargalaxy.api.models.planets.PlanetRetrieveParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUpdateParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUploadImageParams
import com.demoapiscalargalaxy.api.models.planets.PlanetUploadImageResponse
import com.google.errorprone.annotations.MustBeClosed

/** Everything about planets */
interface PlanetService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: (ClientOptions.Builder) -> Unit): PlanetService

    /**
     * Time to play god and create a new planet. What do you think? Ah, don't think too much. What
     * could go wrong anyway?
     */
    fun create(
        params: PlanetCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Planet

    /** @see create */
    fun create(planet: Planet, requestOptions: RequestOptions = RequestOptions.none()): Planet =
        create(PlanetCreateParams.builder().planet(planet).build(), requestOptions)

    /**
     * You'll better learn a little bit more about the planets. It might come in handy once space
     * travel is available for everyone.
     */
    fun retrieve(
        planetId: Long,
        params: PlanetRetrieveParams = PlanetRetrieveParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Planet = retrieve(params.toBuilder().planetId(planetId).build(), requestOptions)

    /** @see retrieve */
    fun retrieve(
        params: PlanetRetrieveParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Planet

    /** @see retrieve */
    fun retrieve(planetId: Long, requestOptions: RequestOptions): Planet =
        retrieve(planetId, PlanetRetrieveParams.none(), requestOptions)

    /** Sometimes you make mistakes, that's fine. No worries, you can update all planets. */
    fun update(
        planetId: Long,
        params: PlanetUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Planet = update(params.toBuilder().planetId(planetId).build(), requestOptions)

    /** @see update */
    fun update(
        params: PlanetUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): Planet

    /**
     * It's easy to say you know them all, but do you really? Retrieve all the planets and check
     * whether you missed one.
     */
    fun list(
        params: PlanetListParams = PlanetListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): PlanetListResponse

    /** @see list */
    fun list(requestOptions: RequestOptions): PlanetListResponse =
        list(PlanetListParams.none(), requestOptions)

    /**
     * This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for
     * planets with life. So, this endpoint is now deprecated and should not be used anymore.
     */
    fun delete(
        planetId: Long,
        params: PlanetDeleteParams = PlanetDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ) = delete(params.toBuilder().planetId(planetId).build(), requestOptions)

    /** @see delete */
    fun delete(params: PlanetDeleteParams, requestOptions: RequestOptions = RequestOptions.none())

    /** @see delete */
    fun delete(planetId: Long, requestOptions: RequestOptions) =
        delete(planetId, PlanetDeleteParams.none(), requestOptions)

    /** Got a crazy good photo of a planet? Share it with the world! */
    fun uploadImage(
        planetId: Long,
        params: PlanetUploadImageParams = PlanetUploadImageParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): PlanetUploadImageResponse =
        uploadImage(params.toBuilder().planetId(planetId).build(), requestOptions)

    /** @see uploadImage */
    fun uploadImage(
        params: PlanetUploadImageParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): PlanetUploadImageResponse

    /** @see uploadImage */
    fun uploadImage(planetId: Long, requestOptions: RequestOptions): PlanetUploadImageResponse =
        uploadImage(planetId, PlanetUploadImageParams.none(), requestOptions)

    /** A view of [PlanetService] that provides access to raw HTTP responses for each method. */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(modifier: (ClientOptions.Builder) -> Unit): PlanetService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /planets`, but is otherwise the same as
         * [PlanetService.create].
         */
        @MustBeClosed
        fun create(
            params: PlanetCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet>

        /** @see create */
        @MustBeClosed
        fun create(
            planet: Planet,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet> =
            create(PlanetCreateParams.builder().planet(planet).build(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /planets/{planetId}`, but is otherwise the same as
         * [PlanetService.retrieve].
         */
        @MustBeClosed
        fun retrieve(
            planetId: Long,
            params: PlanetRetrieveParams = PlanetRetrieveParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet> =
            retrieve(params.toBuilder().planetId(planetId).build(), requestOptions)

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(
            params: PlanetRetrieveParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet>

        /** @see retrieve */
        @MustBeClosed
        fun retrieve(planetId: Long, requestOptions: RequestOptions): HttpResponseFor<Planet> =
            retrieve(planetId, PlanetRetrieveParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `put /planets/{planetId}`, but is otherwise the same as
         * [PlanetService.update].
         */
        @MustBeClosed
        fun update(
            planetId: Long,
            params: PlanetUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet> =
            update(params.toBuilder().planetId(planetId).build(), requestOptions)

        /** @see update */
        @MustBeClosed
        fun update(
            params: PlanetUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<Planet>

        /**
         * Returns a raw HTTP response for `get /planets`, but is otherwise the same as
         * [PlanetService.list].
         */
        @MustBeClosed
        fun list(
            params: PlanetListParams = PlanetListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<PlanetListResponse>

        /** @see list */
        @MustBeClosed
        fun list(requestOptions: RequestOptions): HttpResponseFor<PlanetListResponse> =
            list(PlanetListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /planets/{planetId}`, but is otherwise the same
         * as [PlanetService.delete].
         */
        @MustBeClosed
        fun delete(
            planetId: Long,
            params: PlanetDeleteParams = PlanetDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse = delete(params.toBuilder().planetId(planetId).build(), requestOptions)

        /** @see delete */
        @MustBeClosed
        fun delete(
            params: PlanetDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse

        /** @see delete */
        @MustBeClosed
        fun delete(planetId: Long, requestOptions: RequestOptions): HttpResponse =
            delete(planetId, PlanetDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `post /planets/{planetId}/image`, but is otherwise the
         * same as [PlanetService.uploadImage].
         */
        @MustBeClosed
        fun uploadImage(
            planetId: Long,
            params: PlanetUploadImageParams = PlanetUploadImageParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<PlanetUploadImageResponse> =
            uploadImage(params.toBuilder().planetId(planetId).build(), requestOptions)

        /** @see uploadImage */
        @MustBeClosed
        fun uploadImage(
            params: PlanetUploadImageParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<PlanetUploadImageResponse>

        /** @see uploadImage */
        @MustBeClosed
        fun uploadImage(
            planetId: Long,
            requestOptions: RequestOptions,
        ): HttpResponseFor<PlanetUploadImageResponse> =
            uploadImage(planetId, PlanetUploadImageParams.none(), requestOptions)
    }
}
