// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.services.blocking

import com.demoapiscalargalaxy.api.core.ClientOptions
import com.demoapiscalargalaxy.api.core.UnwrapWebhookParams
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyWebhookException
import com.demoapiscalargalaxy.api.models.webhooks.UnwrapWebhookEvent
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.standardwebhooks.Webhook
import com.standardwebhooks.exceptions.WebhookVerificationException

class WebhookServiceImpl internal constructor(private val clientOptions: ClientOptions) :
    WebhookService {

    private val withRawResponse: WebhookService.WithRawResponse by lazy {
        WithRawResponseImpl(clientOptions)
    }

    override fun withRawResponse(): WebhookService.WithRawResponse = withRawResponse

    override fun withOptions(modifier: (ClientOptions.Builder) -> Unit): WebhookService =
        WebhookServiceImpl(clientOptions.toBuilder().apply(modifier).build())

    override fun unwrap(body: String): UnwrapWebhookEvent =
        try {
            clientOptions.jsonMapper.readValue(body, jacksonTypeRef<UnwrapWebhookEvent>())
        } catch (e: Exception) {
            throw DemoApiScalarGalaxyInvalidDataException("Error parsing body", e)
        }

    override fun unwrap(unwrapParams: UnwrapWebhookParams): UnwrapWebhookEvent {
        val headers = unwrapParams.headers()
        if (headers != null) {
            try {
                val webhookSecret = checkRequired("webhookSecret", unwrapParams.secret())

                val headersMap =
                    headers.names().associateWith { name -> headers.values(name) }.toMap()

                val webhook = Webhook(webhookSecret)
                webhook.verify(unwrapParams.body(), headersMap)
            } catch (e: WebhookVerificationException) {
                throw DemoApiScalarGalaxyWebhookException(
                    "Could not verify webhook event signature",
                    e,
                )
            }
        }
        return unwrap(unwrapParams.body())
    }

    class WithRawResponseImpl internal constructor(private val clientOptions: ClientOptions) :
        WebhookService.WithRawResponse {

        override fun withOptions(
            modifier: (ClientOptions.Builder) -> Unit
        ): WebhookService.WithRawResponse =
            WebhookServiceImpl.WithRawResponseImpl(
                clientOptions.toBuilder().apply(modifier).build()
            )
    }
}
