// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.core

import com.demoapiscalargalaxy.api.core.http.Headers
import com.demoapiscalargalaxy.api.core.http.HttpClient
import com.demoapiscalargalaxy.api.core.http.LoggingHttpClient
import com.demoapiscalargalaxy.api.core.http.PhantomReachableClosingHttpClient
import com.demoapiscalargalaxy.api.core.http.QueryParams
import com.demoapiscalargalaxy.api.core.http.RetryingHttpClient
import com.fasterxml.jackson.databind.json.JsonMapper
import java.time.Clock
import java.time.Duration
import java.util.Base64

/** A class representing the SDK client configuration. */
class ClientOptions
private constructor(
    private val originalHttpClient: HttpClient,
    /**
     * The HTTP client to use in the SDK.
     *
     * Use the one published in `demoApiScalarGalaxy-kotlin-client-okhttp` or implement your own.
     *
     * This class takes ownership of the client and closes it when closed.
     */
    val httpClient: HttpClient,
    /**
     * Whether to throw an exception if any of the Jackson versions detected at runtime are
     * incompatible with the SDK's minimum supported Jackson version (2.13.4).
     *
     * Defaults to true. Use extreme caution when disabling this option. There is no guarantee that
     * the SDK will work correctly when using an incompatible Jackson version.
     */
    val checkJacksonVersionCompatibility: Boolean,
    /**
     * The Jackson JSON mapper to use for serializing and deserializing JSON.
     *
     * Defaults to [com.demoapiscalargalaxy.api.core.jsonMapper]. The default is usually sufficient
     * and rarely needs to be overridden.
     */
    val jsonMapper: JsonMapper,
    /**
     * The interface to use for delaying execution, like during retries.
     *
     * This is primarily useful for using fake delays in tests.
     *
     * Defaults to real execution delays.
     *
     * This class takes ownership of the sleeper and closes it when closed.
     */
    val sleeper: Sleeper,
    /**
     * The clock to use for operations that require timing, like retries.
     *
     * This is primarily useful for using a fake clock in tests.
     *
     * Defaults to [Clock.systemUTC].
     */
    val clock: Clock,
    private val baseUrl: String?,
    /** Headers to send with the request. */
    val headers: Headers,
    /** Query params to send with the request. */
    val queryParams: QueryParams,
    /**
     * Whether to call `validate` on every response before returning it.
     *
     * Setting this to `true` is _not_ forwards compatible with new types from the API for existing
     * fields.
     *
     * Defaults to false, which means the shape of the response will not be validated upfront.
     * Instead, validation will only occur for the parts of the response that are accessed.
     */
    val responseValidation: Boolean,
    /**
     * Sets the maximum time allowed for various parts of an HTTP call's lifecycle, excluding
     * retries.
     *
     * Defaults to [Timeout.default].
     */
    val timeout: Timeout,
    /**
     * The maximum number of times to retry failed requests, with a short exponential backoff
     * between requests.
     *
     * Only the following error types are retried:
     * - Connection errors (for example, due to a network connectivity problem)
     * - 408 Request Timeout
     * - 409 Conflict
     * - 429 Rate Limit
     * - 5xx Internal
     *
     * The API may also explicitly instruct the SDK to retry or not retry a request.
     *
     * Defaults to 2.
     */
    val maxRetries: Int,
    /**
     * The level at which to log request and response information.
     *
     * [fromEnv] will set the level from environment variables. See [LogLevel.fromEnv].
     *
     * Defaults to [LogLevel.fromEnv].
     */
    val logLevel: LogLevel,
    /** JWT Bearer token authentication */
    val bearerAuth: String?,
    val basicAuthUsername: String?,
    val basicAuthPassword: String?,
    /** API key request header */
    val apiKeyHeader: String?,
    /** API key query parameter */
    val apiKeyQuery: String?,
    /** API key browser cookie */
    val apiKeyCookie: String?,
    /** OAuth 2.0 authentication */
    val oAuth2: String?,
    /** OpenID Connect Authentication */
    val openIdConnect: String?,
) {

    init {
        if (checkJacksonVersionCompatibility) {
            checkJacksonVersionCompatibility()
        }
    }

    /**
     * The base URL to use for every request.
     *
     * Defaults to the production environment: `https://galaxy.scalar.com`.
     *
     * The following other environments, with dedicated builder methods, are available:
     * - responds_with_your_request_data: `https://void.scalar.com/{path}`
     */
    fun baseUrl(): String = baseUrl ?: PRODUCTION_URL

    fun toBuilder() = Builder().from(this)

    companion object {

        const val PRODUCTION_URL = "https://galaxy.scalar.com"

        const val RESPONDS_WITH_YOUR_REQUEST_DATA_URL = "https://void.scalar.com/{path}"

        /**
         * Returns a mutable builder for constructing an instance of [ClientOptions].
         *
         * The following fields are required:
         * ```kotlin
         * .httpClient()
         * ```
         */
        fun builder() = Builder()

        /**
         * Returns options configured using system properties and environment variables.
         *
         * @see Builder.fromEnv
         */
        fun fromEnv(): ClientOptions = builder().fromEnv().build()
    }

    /** A builder for [ClientOptions]. */
    class Builder internal constructor() {

        private var httpClient: HttpClient? = null
        private var checkJacksonVersionCompatibility: Boolean = true
        private var jsonMapper: JsonMapper = jsonMapper()
        private var sleeper: Sleeper? = null
        private var clock: Clock = Clock.systemUTC()
        private var baseUrl: String? = null
        private var headers: Headers.Builder = Headers.builder()
        private var queryParams: QueryParams.Builder = QueryParams.builder()
        private var responseValidation: Boolean = false
        private var timeout: Timeout = Timeout.default()
        private var maxRetries: Int = 2
        private var logLevel: LogLevel = LogLevel.fromEnv()
        private var bearerAuth: String? = null
        private var basicAuthUsername: String? = null
        private var basicAuthPassword: String? = null
        private var apiKeyHeader: String? = null
        private var apiKeyQuery: String? = null
        private var apiKeyCookie: String? = null
        private var oAuth2: String? = null
        private var openIdConnect: String? = null

        internal fun from(clientOptions: ClientOptions) = apply {
            httpClient = clientOptions.originalHttpClient
            checkJacksonVersionCompatibility = clientOptions.checkJacksonVersionCompatibility
            jsonMapper = clientOptions.jsonMapper
            sleeper = clientOptions.sleeper
            clock = clientOptions.clock
            baseUrl = clientOptions.baseUrl
            headers = clientOptions.headers.toBuilder()
            queryParams = clientOptions.queryParams.toBuilder()
            responseValidation = clientOptions.responseValidation
            timeout = clientOptions.timeout
            maxRetries = clientOptions.maxRetries
            logLevel = clientOptions.logLevel
            bearerAuth = clientOptions.bearerAuth
            basicAuthUsername = clientOptions.basicAuthUsername
            basicAuthPassword = clientOptions.basicAuthPassword
            apiKeyHeader = clientOptions.apiKeyHeader
            apiKeyQuery = clientOptions.apiKeyQuery
            apiKeyCookie = clientOptions.apiKeyCookie
            oAuth2 = clientOptions.oAuth2
            openIdConnect = clientOptions.openIdConnect
        }

        /**
         * The HTTP client to use in the SDK.
         *
         * Use the one published in `demoApiScalarGalaxy-kotlin-client-okhttp` or implement your
         * own.
         *
         * This class takes ownership of the client and closes it when closed.
         */
        fun httpClient(httpClient: HttpClient) = apply {
            this.httpClient = PhantomReachableClosingHttpClient(httpClient)
        }

        /**
         * Whether to throw an exception if any of the Jackson versions detected at runtime are
         * incompatible with the SDK's minimum supported Jackson version (2.13.4).
         *
         * Defaults to true. Use extreme caution when disabling this option. There is no guarantee
         * that the SDK will work correctly when using an incompatible Jackson version.
         */
        fun checkJacksonVersionCompatibility(checkJacksonVersionCompatibility: Boolean) = apply {
            this.checkJacksonVersionCompatibility = checkJacksonVersionCompatibility
        }

        /**
         * The Jackson JSON mapper to use for serializing and deserializing JSON.
         *
         * Defaults to [com.demoapiscalargalaxy.api.core.jsonMapper]. The default is usually
         * sufficient and rarely needs to be overridden.
         */
        fun jsonMapper(jsonMapper: JsonMapper) = apply { this.jsonMapper = jsonMapper }

        /**
         * The interface to use for delaying execution, like during retries.
         *
         * This is primarily useful for using fake delays in tests.
         *
         * Defaults to real execution delays.
         *
         * This class takes ownership of the sleeper and closes it when closed.
         */
        fun sleeper(sleeper: Sleeper) = apply { this.sleeper = PhantomReachableSleeper(sleeper) }

        /**
         * The clock to use for operations that require timing, like retries.
         *
         * This is primarily useful for using a fake clock in tests.
         *
         * Defaults to [Clock.systemUTC].
         */
        fun clock(clock: Clock) = apply { this.clock = clock }

        /**
         * The base URL to use for every request.
         *
         * Defaults to the production environment: `https://galaxy.scalar.com`.
         *
         * The following other environments, with dedicated builder methods, are available:
         * - responds_with_your_request_data: `https://void.scalar.com/{path}`
         */
        fun baseUrl(baseUrl: String?) = apply { this.baseUrl = baseUrl }

        /** Sets [baseUrl] to `https://void.scalar.com/{path}`. */
        fun responds_with_your_request_data() = baseUrl(RESPONDS_WITH_YOUR_REQUEST_DATA_URL)

        /**
         * Whether to call `validate` on every response before returning it.
         *
         * Setting this to `true` is _not_ forwards compatible with new types from the API for
         * existing fields.
         *
         * Defaults to false, which means the shape of the response will not be validated upfront.
         * Instead, validation will only occur for the parts of the response that are accessed.
         */
        fun responseValidation(responseValidation: Boolean) = apply {
            this.responseValidation = responseValidation
        }

        /**
         * Sets the maximum time allowed for various parts of an HTTP call's lifecycle, excluding
         * retries.
         *
         * Defaults to [Timeout.default].
         */
        fun timeout(timeout: Timeout) = apply { this.timeout = timeout }

        /**
         * Sets the maximum time allowed for a complete HTTP call, not including retries.
         *
         * See [Timeout.request] for more details.
         *
         * For fine-grained control, pass a [Timeout] object.
         */
        fun timeout(timeout: Duration) = timeout(Timeout.builder().request(timeout).build())

        /**
         * The maximum number of times to retry failed requests, with a short exponential backoff
         * between requests.
         *
         * Only the following error types are retried:
         * - Connection errors (for example, due to a network connectivity problem)
         * - 408 Request Timeout
         * - 409 Conflict
         * - 429 Rate Limit
         * - 5xx Internal
         *
         * The API may also explicitly instruct the SDK to retry or not retry a request.
         *
         * Defaults to 2.
         */
        fun maxRetries(maxRetries: Int) = apply { this.maxRetries = maxRetries }

        /**
         * The level at which to log request and response information.
         *
         * [fromEnv] will set the level from environment variables. See [LogLevel.fromEnv].
         *
         * Defaults to [LogLevel.fromEnv].
         */
        fun logLevel(logLevel: LogLevel) = apply { this.logLevel = logLevel }

        /** JWT Bearer token authentication */
        fun bearerAuth(bearerAuth: String?) = apply { this.bearerAuth = bearerAuth }

        fun basicAuthUsername(basicAuthUsername: String?) = apply {
            this.basicAuthUsername = basicAuthUsername
        }

        fun basicAuthPassword(basicAuthPassword: String?) = apply {
            this.basicAuthPassword = basicAuthPassword
        }

        /** API key request header */
        fun apiKeyHeader(apiKeyHeader: String?) = apply { this.apiKeyHeader = apiKeyHeader }

        /** API key query parameter */
        fun apiKeyQuery(apiKeyQuery: String?) = apply { this.apiKeyQuery = apiKeyQuery }

        /** API key browser cookie */
        fun apiKeyCookie(apiKeyCookie: String?) = apply { this.apiKeyCookie = apiKeyCookie }

        /** OAuth 2.0 authentication */
        fun oAuth2(oAuth2: String?) = apply { this.oAuth2 = oAuth2 }

        /** OpenID Connect Authentication */
        fun openIdConnect(openIdConnect: String?) = apply { this.openIdConnect = openIdConnect }

        fun headers(headers: Headers) = apply {
            this.headers.clear()
            putAllHeaders(headers)
        }

        fun headers(headers: Map<String, Iterable<String>>) = apply {
            this.headers.clear()
            putAllHeaders(headers)
        }

        fun putHeader(name: String, value: String) = apply { headers.put(name, value) }

        fun putHeaders(name: String, values: Iterable<String>) = apply { headers.put(name, values) }

        fun putAllHeaders(headers: Headers) = apply { this.headers.putAll(headers) }

        fun putAllHeaders(headers: Map<String, Iterable<String>>) = apply {
            this.headers.putAll(headers)
        }

        fun replaceHeaders(name: String, value: String) = apply { headers.replace(name, value) }

        fun replaceHeaders(name: String, values: Iterable<String>) = apply {
            headers.replace(name, values)
        }

        fun replaceAllHeaders(headers: Headers) = apply { this.headers.replaceAll(headers) }

        fun replaceAllHeaders(headers: Map<String, Iterable<String>>) = apply {
            this.headers.replaceAll(headers)
        }

        fun removeHeaders(name: String) = apply { headers.remove(name) }

        fun removeAllHeaders(names: Set<String>) = apply { headers.removeAll(names) }

        fun queryParams(queryParams: QueryParams) = apply {
            this.queryParams.clear()
            putAllQueryParams(queryParams)
        }

        fun queryParams(queryParams: Map<String, Iterable<String>>) = apply {
            this.queryParams.clear()
            putAllQueryParams(queryParams)
        }

        fun putQueryParam(key: String, value: String) = apply { queryParams.put(key, value) }

        fun putQueryParams(key: String, values: Iterable<String>) = apply {
            queryParams.put(key, values)
        }

        fun putAllQueryParams(queryParams: QueryParams) = apply {
            this.queryParams.putAll(queryParams)
        }

        fun putAllQueryParams(queryParams: Map<String, Iterable<String>>) = apply {
            this.queryParams.putAll(queryParams)
        }

        fun replaceQueryParams(key: String, value: String) = apply {
            queryParams.replace(key, value)
        }

        fun replaceQueryParams(key: String, values: Iterable<String>) = apply {
            queryParams.replace(key, values)
        }

        fun replaceAllQueryParams(queryParams: QueryParams) = apply {
            this.queryParams.replaceAll(queryParams)
        }

        fun replaceAllQueryParams(queryParams: Map<String, Iterable<String>>) = apply {
            this.queryParams.replaceAll(queryParams)
        }

        fun removeQueryParams(key: String) = apply { queryParams.remove(key) }

        fun removeAllQueryParams(keys: Set<String>) = apply { queryParams.removeAll(keys) }

        fun timeout(): Timeout = timeout

        /**
         * Updates configuration using system properties and environment variables.
         *
         * See this table for the available options:
         *
         * |Setter             |System property                          |Environment variable              |Required|Default value                |
         * |-------------------|-----------------------------------------|----------------------------------|--------|-----------------------------|
         * |`bearerAuth`       |`officialgalaxytesting.bearerAuth`       |`BEARER_AUTH`                     |false   |-                            |
         * |`basicAuthUsername`|`officialgalaxytesting.basicAuthUsername`|`BASIC_AUTH_USERNAME`             |false   |-                            |
         * |`basicAuthPassword`|`officialgalaxytesting.basicAuthPassword`|`BASIC_AUTH_PASSWORD`             |false   |-                            |
         * |`apiKeyHeader`     |`officialgalaxytesting.apiKeyHeader`     |`API_KEY_HEADER`                  |false   |-                            |
         * |`apiKeyQuery`      |`officialgalaxytesting.apiKeyQuery`      |`API_KEY_QUERY`                   |false   |-                            |
         * |`apiKeyCookie`     |`officialgalaxytesting.apiKeyCookie`     |`API_KEY_COOKIE`                  |false   |-                            |
         * |`oAuth2`           |`officialgalaxytesting.oAuth2`           |`O_AUTH2`                         |false   |-                            |
         * |`openIdConnect`    |`officialgalaxytesting.openIdConnect`    |`OPEN_ID_CONNECT`                 |false   |-                            |
         * |`baseUrl`          |`officialgalaxytesting.baseUrl`          |`OFFICIAL_GALAXY_TESTING_BASE_URL`|true    |`"https://galaxy.scalar.com"`|
         *
         * System properties take precedence over environment variables.
         */
        fun fromEnv() = apply {
            logLevel(LogLevel.fromEnv())
            (System.getProperty("officialgalaxytesting.baseUrl")
                    ?: System.getenv("OFFICIAL_GALAXY_TESTING_BASE_URL"))
                ?.let { baseUrl(it) }
            (System.getProperty("officialgalaxytesting.bearerAuth") ?: System.getenv("BEARER_AUTH"))
                ?.let { bearerAuth(it) }
            (System.getProperty("officialgalaxytesting.basicAuthUsername")
                    ?: System.getenv("BASIC_AUTH_USERNAME"))
                ?.let { basicAuthUsername(it) }
            (System.getProperty("officialgalaxytesting.basicAuthPassword")
                    ?: System.getenv("BASIC_AUTH_PASSWORD"))
                ?.let { basicAuthPassword(it) }
            (System.getProperty("officialgalaxytesting.apiKeyHeader")
                    ?: System.getenv("API_KEY_HEADER"))
                ?.let { apiKeyHeader(it) }
            (System.getProperty("officialgalaxytesting.apiKeyQuery")
                    ?: System.getenv("API_KEY_QUERY"))
                ?.let { apiKeyQuery(it) }
            (System.getProperty("officialgalaxytesting.apiKeyCookie")
                    ?: System.getenv("API_KEY_COOKIE"))
                ?.let { apiKeyCookie(it) }
            (System.getProperty("officialgalaxytesting.oAuth2") ?: System.getenv("O_AUTH2"))?.let {
                oAuth2(it)
            }
            (System.getProperty("officialgalaxytesting.openIdConnect")
                    ?: System.getenv("OPEN_ID_CONNECT"))
                ?.let { openIdConnect(it) }
            System.getenv("OFFICIAL_GALAXY_TESTING_CUSTOM_HEADERS")?.let { customHeadersEnv ->
                for (line in customHeadersEnv.split("\n")) {
                    val colon = line.indexOf(':')
                    if (colon >= 0) {
                        putHeader(line.substring(0, colon).trim(), line.substring(colon + 1).trim())
                    }
                }
            }
        }

        /**
         * Returns an immutable instance of [ClientOptions].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .httpClient()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): ClientOptions {
            val httpClient = checkRequired("httpClient", httpClient)
            val sleeper = sleeper ?: PhantomReachableSleeper(DefaultSleeper())

            val headers = Headers.builder()
            val queryParams = QueryParams.builder()
            headers.put("X-Scalar-Lang", "kotlin")
            headers.put("X-Scalar-Arch", getOsArch())
            headers.put("X-Scalar-OS", getOsName())
            headers.put("X-Scalar-OS-Version", getOsVersion())
            headers.put("X-Scalar-Package-Version", getPackageVersion())
            headers.put("X-Scalar-Runtime", "JRE")
            headers.put("X-Scalar-Runtime-Version", getJavaVersion())
            headers.put("X-Scalar-Kotlin-Version", KotlinVersion.CURRENT.toString())
            // We replace after all the default headers to allow end-users to overwrite them.
            headers.replaceAll(this.headers.build())
            queryParams.replaceAll(this.queryParams.build())
            bearerAuth?.let {
                if (!it.isEmpty()) {
                    headers.replace("Authorization", "Bearer $it")
                }
            }
            apiKeyHeader?.let {
                if (!it.isEmpty()) {
                    headers.replace("X-API-Key", it)
                }
            }
            apiKeyQuery?.let {
                if (!it.isEmpty()) {
                    queryParams.replace("api_key", it)
                }
            }
            oAuth2?.let {
                if (!it.isEmpty()) {
                    headers.replace("Authorization", "Bearer $it")
                }
            }
            openIdConnect?.let {
                if (!it.isEmpty()) {
                    headers.replace("Authorization", "Bearer $it")
                }
            }
            val cookieParts = mutableListOf<String>()
            apiKeyCookie?.let {
                if (!it.isEmpty()) {
                    cookieParts.add("api_key=" + it)
                }
            }
            if (cookieParts.isNotEmpty()) {
                headers.replace("Cookie", cookieParts.joinToString("; "))
            }
            basicAuthUsername?.let { username ->
                basicAuthPassword?.let { password ->
                    if (!username.isEmpty() && !password.isEmpty()) {
                        headers.replace(
                            "Authorization",
                            "Basic ${Base64.getEncoder().encodeToString("$username:$password".toByteArray())}",
                        )
                    }
                }
            }

            return ClientOptions(
                httpClient,
                RetryingHttpClient.builder()
                    .httpClient(
                        LoggingHttpClient.builder()
                            .httpClient(httpClient)
                            .clock(clock)
                            .level(logLevel)
                            .build()
                    )
                    .sleeper(sleeper)
                    .clock(clock)
                    .maxRetries(maxRetries)
                    .build(),
                checkJacksonVersionCompatibility,
                jsonMapper,
                sleeper,
                clock,
                baseUrl,
                headers.build(),
                queryParams.build(),
                responseValidation,
                timeout,
                maxRetries,
                logLevel,
                bearerAuth,
                basicAuthUsername,
                basicAuthPassword,
                apiKeyHeader,
                apiKeyQuery,
                apiKeyCookie,
                oAuth2,
                openIdConnect,
            )
        }
    }

    /**
     * Closes these client options, relinquishing any underlying resources.
     *
     * This is purposefully not inherited from [AutoCloseable] because the client options are
     * long-lived and usually should not be synchronously closed via try-with-resources.
     *
     * It's also usually not necessary to call this method at all. the default client automatically
     * releases threads and connections if they remain idle, but if you are writing an application
     * that needs to aggressively release unused resources, then you may call this method.
     */
    fun close() {
        httpClient.close()
        sleeper.close()
    }
}
