// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.proguard

import com.demoapiscalargalaxy.api.client.okhttp.DemoApiScalarGalaxyOkHttpClient
import com.demoapiscalargalaxy.api.core.jsonMapper
import com.demoapiscalargalaxy.api.models.celestialBodies.CelestialBody
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.fasterxml.jackson.core.type.TypeReference
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

/**
 * Proves the ProGuard/R8 keep rules this SDK publishes are enough for a consumer to shrink it.
 *
 * Run under JUnit by `./gradlew test`, and out of the ProGuard- and R8-shrunk jars by `./gradlew
 * testProGuard testR8`. A failure in the shrunk runs alone means the published keep rules are too
 * narrow, not that the SDK is broken.
 */
internal class ProGuardCompatibilityTest {

    companion object {

        /**
         * Entry point the shrunk jars are executed through.
         *
         * The tests are called by name rather than discovered: a JUnit launcher inside a shrunk jar
         * would need keep rules of its own, and a missing one would read as an SDK failure.
         */
        @JvmStatic
        fun main(args: Array<String>) {
            val test = ProGuardCompatibilityTest()
            test.keepRulesAreOnTheClasspath()
            test.clientResolvesEveryService()
            test.planetRoundtrips()
            test.celestialBodyRoundtrips()
        }
    }

    @Test
    fun keepRulesAreOnTheClasspath() {
        assertNotNull(
            javaClass.classLoader.getResourceAsStream(
                "META-INF/proguard/demoApiScalarGalaxy-kotlin-core.pro"
            )
        )
    }

    @Test
    fun clientResolvesEveryService() {
        val client =
            DemoApiScalarGalaxyOkHttpClient.builder()
                .bearerAuth("My Bearer Auth")
                .basicAuthUsername("My Basic Auth Username")
                .basicAuthPassword("My Basic Auth Password")
                .apiKeyHeader("My Api Key Header")
                .apiKeyQuery("My Api Key Query")
                .apiKeyCookie("My Api Key Cookie")
                .oAuth2("My O Auth2")
                .openIdConnect("My Open Id Connect")
                .build()

        assertNotNull(client.planets())
        assertNotNull(client.celestialBodies())
        assertNotNull(client.authentication())
        assertNotNull(client.webhooks())
    }

    @Test
    fun planetRoundtrips() {
        val planet = Planet.builder().name("Mars").type(Planet.Type.of("terrestrial")).build()
        val planetJson = jsonMapper().writeValueAsString(planet)

        assertEquals(
            planetJson,
            jsonMapper()
                .writeValueAsString(
                    jsonMapper().readValue(planetJson, object : TypeReference<Planet>() {})
                ),
        )
    }

    @Test
    fun celestialBodyRoundtrips() {
        val celestialBody =
            CelestialBody.ofPlanet(
                Planet.builder().name("Mars").type(Planet.Type.of("terrestrial")).build()
            )
        val celestialBodyJson = jsonMapper().writeValueAsString(celestialBody)

        assertEquals(
            celestialBodyJson,
            jsonMapper()
                .writeValueAsString(
                    jsonMapper()
                        .readValue(celestialBodyJson, object : TypeReference<CelestialBody>() {})
                ),
        )
    }
}
