// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.celestialBodies

import com.demoapiscalargalaxy.api.core.BaseDeserializer
import com.demoapiscalargalaxy.api.core.BaseSerializer
import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.getOrThrow
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.Satellite
import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.ObjectCodec
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.util.Objects

/** A celestial body which can be either a planet or a satellite */
@JsonDeserialize(using = CelestialBody.Deserializer::class)
@JsonSerialize(using = CelestialBody.Serializer::class)
class CelestialBody
private constructor(
    private val planet: Planet? = null,
    private val satellite: Satellite? = null,
    private val _json: JsonValue? = null,
) {

    /** A planet in the Scalar Galaxy */
    fun planet(): Planet? = planet

    /** Every satellite in the Scalar Galaxy */
    fun satellite(): Satellite? = satellite

    fun isPlanet(): Boolean = planet != null

    fun isSatellite(): Boolean = satellite != null

    /** A planet in the Scalar Galaxy */
    fun asPlanet(): Planet = planet.getOrThrow("planet")

    /** Every satellite in the Scalar Galaxy */
    fun asSatellite(): Satellite = satellite.getOrThrow("satellite")

    fun _json(): JsonValue? = _json

    /**
     * Maps this instance's current variant to a value of type [T] using the given [visitor].
     *
     * Note that this method is _not_ forwards compatible with new variants from the API, unless
     * [visitor] overrides [Visitor.unknown]. To handle variants not known to this version of the
     * SDK gracefully, consider overriding [Visitor.unknown]:
     * ```kotlin
     * import com.demoapiscalargalaxy.api.core.JsonValue
     *
     * val result: String? =
     *     celestialBody.accept(
     *         object : CelestialBody.Visitor<String?> {
     *             override fun visitPlanet(planet: Planet): String? = planet.toString()
     *
     *             // ...
     *
     *             override fun unknown(json: JsonValue?): String? {
     *                 // Or inspect the `json`.
     *                 return null
     *             }
     *         }
     *     )
     * ```
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if [Visitor.unknown] is not overridden in
     *   [visitor] and the current variant is unknown.
     */
    fun <T> accept(visitor: Visitor<T>): T =
        when {
            planet != null -> visitor.visitPlanet(planet)
            satellite != null -> visitor.visitSatellite(satellite)
            else -> visitor.unknown(_json)
        }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
     *   match its expected type.
     */
    fun validate(): CelestialBody = apply {
        if (validated) {
            return@apply
        }

        accept(
            object : Visitor<Unit> {
                override fun visitPlanet(planet: Planet) {
                    planet.validate()
                }

                override fun visitSatellite(satellite: Satellite) {
                    satellite.validate()
                }
            }
        )
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DemoApiScalarGalaxyInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        accept(
            object : Visitor<Int> {
                override fun visitPlanet(planet: Planet) = planet.validity()

                override fun visitSatellite(satellite: Satellite) = satellite.validity()

                override fun unknown(json: JsonValue?) = 0
            }
        )

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is CelestialBody && planet == other.planet && satellite == other.satellite
    }

    override fun hashCode(): Int = Objects.hash(planet, satellite)

    override fun toString(): String =
        when {
            planet != null -> "CelestialBody{planet=$planet}"
            satellite != null -> "CelestialBody{satellite=$satellite}"
            _json != null -> "CelestialBody{_unknown=$_json}"
            else -> throw IllegalStateException("Invalid CelestialBody")
        }

    companion object {

        /** A planet in the Scalar Galaxy */
        fun ofPlanet(planet: Planet) = CelestialBody(planet = planet)

        /** Every satellite in the Scalar Galaxy */
        fun ofSatellite(satellite: Satellite) = CelestialBody(satellite = satellite)
    }

    /**
     * An interface that defines how to map each variant of [CelestialBody] to a value of type [T].
     */
    interface Visitor<out T> {

        /** A planet in the Scalar Galaxy */
        fun visitPlanet(planet: Planet): T

        /** Every satellite in the Scalar Galaxy */
        fun visitSatellite(satellite: Satellite): T

        /**
         * Maps an unknown variant of [CelestialBody] to a value of type [T].
         *
         * An instance of [CelestialBody] can contain an unknown variant if it was deserialized from
         * data that doesn't match any known variant. For example, if the SDK is on an older version
         * than the API, then the API may respond with new variants that the SDK is unaware of.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException in the default implementation.
         */
        fun unknown(json: JsonValue?): T {
            throw DemoApiScalarGalaxyInvalidDataException("Unknown CelestialBody: $json")
        }
    }

    internal class Deserializer : BaseDeserializer<CelestialBody>(CelestialBody::class) {

        override fun ObjectCodec.deserialize(node: JsonNode): CelestialBody {
            val json = JsonValue.fromJsonNode(node)
            val type = json.asObject()?.get("type")?.asString()

            when (type) {
                "planet" -> {
                    return tryDeserialize(node, jacksonTypeRef<Planet>())?.let {
                        CelestialBody(planet = it, _json = json)
                    } ?: CelestialBody(_json = json)
                }
                "satellite" -> {
                    return tryDeserialize(node, jacksonTypeRef<Satellite>())?.let {
                        CelestialBody(satellite = it, _json = json)
                    } ?: CelestialBody(_json = json)
                }
            }

            return CelestialBody(_json = json)
        }
    }

    internal class Serializer : BaseSerializer<CelestialBody>(CelestialBody::class) {

        override fun serialize(
            value: CelestialBody,
            generator: JsonGenerator,
            provider: SerializerProvider,
        ) {
            when {
                value.planet != null -> generator.writeObject(value.planet)
                value.satellite != null -> generator.writeObject(value.satellite)
                value._json != null -> generator.writeObject(value._json)
                else -> throw IllegalStateException("Invalid CelestialBody")
            }
        }
    }
}
