// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.celestialBodies

import com.demoapiscalargalaxy.api.core.Params
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.core.http.Headers
import com.demoapiscalargalaxy.api.core.http.QueryParams
import com.demoapiscalargalaxy.api.models.planets.Planet
import com.demoapiscalargalaxy.api.models.planets.Satellite
import java.util.Objects

/** Create a celestial body */
class CelestialBodyCreateParams
private constructor(
    private val celestialBody: CelestialBody,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
) : Params {

    /** A celestial body which can be either a planet or a satellite */
    fun celestialBody(): CelestialBody = celestialBody

    /** Additional headers to send with the request. */
    fun _additionalHeaders(): Headers = additionalHeaders

    /** Additional query param to send with the request. */
    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [CelestialBodyCreateParams].
         *
         * The following fields are required:
         * ```kotlin
         * .celestialBody()
         * ```
         */
        fun builder() = Builder()
    }

    /** A builder for [CelestialBodyCreateParams]. */
    class Builder internal constructor() {

        private var celestialBody: CelestialBody? = null
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()

        internal fun from(celestialBodyCreateParams: CelestialBodyCreateParams) = apply {
            celestialBody = celestialBodyCreateParams.celestialBody
            additionalHeaders = celestialBodyCreateParams.additionalHeaders.toBuilder()
            additionalQueryParams = celestialBodyCreateParams.additionalQueryParams.toBuilder()
        }

        /** A celestial body which can be either a planet or a satellite */
        fun celestialBody(celestialBody: CelestialBody) = apply {
            this.celestialBody = celestialBody
        }

        /** Alias for calling [celestialBody] with `CelestialBody.ofPlanet(planet)`. */
        fun celestialBody(planet: Planet) = celestialBody(CelestialBody.ofPlanet(planet))

        /** Alias for calling [celestialBody] with `CelestialBody.ofSatellite(satellite)`. */
        fun celestialBody(satellite: Satellite) =
            celestialBody(CelestialBody.ofSatellite(satellite))

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        /**
         * Returns an immutable instance of [CelestialBodyCreateParams].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .celestialBody()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): CelestialBodyCreateParams =
            CelestialBodyCreateParams(
                checkRequired("celestialBody", celestialBody),
                additionalHeaders.build(),
                additionalQueryParams.build(),
            )
    }

    fun _body(): CelestialBody = celestialBody

    override fun _headers(): Headers = additionalHeaders

    override fun _queryParams(): QueryParams = additionalQueryParams

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is CelestialBodyCreateParams &&
            celestialBody == other.celestialBody &&
            additionalHeaders == other.additionalHeaders &&
            additionalQueryParams == other.additionalQueryParams
    }

    override fun hashCode(): Int =
        Objects.hash(celestialBody, additionalHeaders, additionalQueryParams)

    override fun toString() =
        "CelestialBodyCreateParams{celestialBody=$celestialBody, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams}"
}
