// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.planets

import com.demoapiscalargalaxy.api.core.Enum
import com.demoapiscalargalaxy.api.core.ExcludeMissing
import com.demoapiscalargalaxy.api.core.JsonField
import com.demoapiscalargalaxy.api.core.JsonMissing
import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.checkKnown
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.core.toImmutable
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.demoapiscalargalaxy.api.models.authentication.User
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime
import java.util.Collections
import java.util.Objects

/** A planet in the Scalar Galaxy */
class Planet
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val id: JsonField<Long>,
    private val name: JsonField<String>,
    private val description: JsonField<String>,
    private val type: JsonField<Type>,
    private val habitabilityIndex: JsonField<Float>,
    private val physicalProperties: JsonField<PhysicalProperties>,
    private val atmosphere: JsonField<List<Atmosphere>>,
    private val discoveredAt: JsonField<OffsetDateTime>,
    private val image: JsonField<String>,
    private val satellites: JsonField<List<Satellite>>,
    private val creator: JsonField<User>,
    private val tags: JsonField<List<String>>,
    private val lastUpdated: JsonField<OffsetDateTime>,
    private val successCallbackUrl: JsonField<String>,
    private val failureCallbackUrl: JsonField<String>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("id") @ExcludeMissing id: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("name") @ExcludeMissing name: JsonField<String> = JsonMissing.of(),
        @JsonProperty("description")
        @ExcludeMissing
        description: JsonField<String> = JsonMissing.of(),
        @JsonProperty("type") @ExcludeMissing type: JsonField<Type> = JsonMissing.of(),
        @JsonProperty("habitabilityIndex")
        @ExcludeMissing
        habitabilityIndex: JsonField<Float> = JsonMissing.of(),
        @JsonProperty("physicalProperties")
        @ExcludeMissing
        physicalProperties: JsonField<PhysicalProperties> = JsonMissing.of(),
        @JsonProperty("atmosphere")
        @ExcludeMissing
        atmosphere: JsonField<List<Atmosphere>> = JsonMissing.of(),
        @JsonProperty("discoveredAt")
        @ExcludeMissing
        discoveredAt: JsonField<OffsetDateTime> = JsonMissing.of(),
        @JsonProperty("image") @ExcludeMissing image: JsonField<String> = JsonMissing.of(),
        @JsonProperty("satellites")
        @ExcludeMissing
        satellites: JsonField<List<Satellite>> = JsonMissing.of(),
        @JsonProperty("creator") @ExcludeMissing creator: JsonField<User> = JsonMissing.of(),
        @JsonProperty("tags") @ExcludeMissing tags: JsonField<List<String>> = JsonMissing.of(),
        @JsonProperty("lastUpdated")
        @ExcludeMissing
        lastUpdated: JsonField<OffsetDateTime> = JsonMissing.of(),
        @JsonProperty("successCallbackUrl")
        @ExcludeMissing
        successCallbackUrl: JsonField<String> = JsonMissing.of(),
        @JsonProperty("failureCallbackUrl")
        @ExcludeMissing
        failureCallbackUrl: JsonField<String> = JsonMissing.of(),
    ) : this(
        id,
        name,
        description,
        type,
        habitabilityIndex,
        physicalProperties,
        atmosphere,
        discoveredAt,
        image,
        satellites,
        creator,
        tags,
        lastUpdated,
        successCallbackUrl,
        failureCallbackUrl,
        mutableMapOf(),
    )

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type or
     *   is unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun id(): Long = id.getRequired("id")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type or
     *   is unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun name(): String = name.getRequired("name")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun description(): String? = description.getNullable("description")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type or
     *   is unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun type(): Type = type.getRequired("type")

    /**
     * A score from 0 to 1 indicating potential habitability
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun habitabilityIndex(): Float? = habitabilityIndex.getNullable("habitabilityIndex")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun physicalProperties(): PhysicalProperties? =
        physicalProperties.getNullable("physicalProperties")

    /**
     * Atmospheric composition
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun atmosphere(): List<Atmosphere>? = atmosphere.getNullable("atmosphere")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun discoveredAt(): OffsetDateTime? = discoveredAt.getNullable("discoveredAt")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun image(): String? = image.getNullable("image")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun satellites(): List<Satellite>? = satellites.getNullable("satellites")

    /**
     * A user
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun creator(): User? = creator.getNullable("creator")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun tags(): List<String>? = tags.getNullable("tags")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun lastUpdated(): OffsetDateTime? = lastUpdated.getNullable("lastUpdated")

    /**
     * URL which gets invoked upon a successful operation
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun successCallbackUrl(): String? = successCallbackUrl.getNullable("successCallbackUrl")

    /**
     * URL which gets invoked upon a failed operation
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun failureCallbackUrl(): String? = failureCallbackUrl.getNullable("failureCallbackUrl")

    /**
     * Returns the raw JSON value of [id].
     *
     * Unlike [id], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("id") @ExcludeMissing fun _id(): JsonField<Long> = id

    /**
     * Returns the raw JSON value of [name].
     *
     * Unlike [name], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("name") @ExcludeMissing fun _name(): JsonField<String> = name

    /**
     * Returns the raw JSON value of [description].
     *
     * Unlike [description], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("description") @ExcludeMissing fun _description(): JsonField<String> = description

    /**
     * Returns the raw JSON value of [type].
     *
     * Unlike [type], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("type") @ExcludeMissing fun _type(): JsonField<Type> = type

    /**
     * Returns the raw JSON value of [habitabilityIndex].
     *
     * Unlike [habitabilityIndex], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("habitabilityIndex")
    @ExcludeMissing
    fun _habitabilityIndex(): JsonField<Float> = habitabilityIndex

    /**
     * Returns the raw JSON value of [physicalProperties].
     *
     * Unlike [physicalProperties], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("physicalProperties")
    @ExcludeMissing
    fun _physicalProperties(): JsonField<PhysicalProperties> = physicalProperties

    /**
     * Returns the raw JSON value of [atmosphere].
     *
     * Unlike [atmosphere], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("atmosphere")
    @ExcludeMissing
    fun _atmosphere(): JsonField<List<Atmosphere>> = atmosphere

    /**
     * Returns the raw JSON value of [discoveredAt].
     *
     * Unlike [discoveredAt], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("discoveredAt")
    @ExcludeMissing
    fun _discoveredAt(): JsonField<OffsetDateTime> = discoveredAt

    /**
     * Returns the raw JSON value of [image].
     *
     * Unlike [image], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("image") @ExcludeMissing fun _image(): JsonField<String> = image

    /**
     * Returns the raw JSON value of [satellites].
     *
     * Unlike [satellites], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("satellites")
    @ExcludeMissing
    fun _satellites(): JsonField<List<Satellite>> = satellites

    /**
     * Returns the raw JSON value of [creator].
     *
     * Unlike [creator], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("creator") @ExcludeMissing fun _creator(): JsonField<User> = creator

    /**
     * Returns the raw JSON value of [tags].
     *
     * Unlike [tags], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("tags") @ExcludeMissing fun _tags(): JsonField<List<String>> = tags

    /**
     * Returns the raw JSON value of [lastUpdated].
     *
     * Unlike [lastUpdated], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("lastUpdated")
    @ExcludeMissing
    fun _lastUpdated(): JsonField<OffsetDateTime> = lastUpdated

    /**
     * Returns the raw JSON value of [successCallbackUrl].
     *
     * Unlike [successCallbackUrl], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("successCallbackUrl")
    @ExcludeMissing
    fun _successCallbackUrl(): JsonField<String> = successCallbackUrl

    /**
     * Returns the raw JSON value of [failureCallbackUrl].
     *
     * Unlike [failureCallbackUrl], this method doesn't throw if the JSON field has an unexpected
     * type.
     */
    @JsonProperty("failureCallbackUrl")
    @ExcludeMissing
    fun _failureCallbackUrl(): JsonField<String> = failureCallbackUrl

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [Planet].
         *
         * The following fields are required:
         * ```kotlin
         * .name()
         * .type()
         * ```
         */
        fun builder() = Builder()
    }

    /** A builder for [Planet]. */
    class Builder internal constructor() {

        private var id: JsonField<Long> = JsonMissing.of()
        private var name: JsonField<String>? = null
        private var description: JsonField<String> = JsonMissing.of()
        private var type: JsonField<Type>? = null
        private var habitabilityIndex: JsonField<Float> = JsonMissing.of()
        private var physicalProperties: JsonField<PhysicalProperties> = JsonMissing.of()
        private var atmosphere: JsonField<MutableList<Atmosphere>>? = null
        private var discoveredAt: JsonField<OffsetDateTime> = JsonMissing.of()
        private var image: JsonField<String> = JsonMissing.of()
        private var satellites: JsonField<MutableList<Satellite>>? = null
        private var creator: JsonField<User> = JsonMissing.of()
        private var tags: JsonField<MutableList<String>>? = null
        private var lastUpdated: JsonField<OffsetDateTime> = JsonMissing.of()
        private var successCallbackUrl: JsonField<String> = JsonMissing.of()
        private var failureCallbackUrl: JsonField<String> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(planet: Planet) = apply {
            id = planet.id
            name = planet.name
            description = planet.description
            type = planet.type
            habitabilityIndex = planet.habitabilityIndex
            physicalProperties = planet.physicalProperties
            atmosphere = planet.atmosphere.map { it.toMutableList() }
            discoveredAt = planet.discoveredAt
            image = planet.image
            satellites = planet.satellites.map { it.toMutableList() }
            creator = planet.creator
            tags = planet.tags.map { it.toMutableList() }
            lastUpdated = planet.lastUpdated
            successCallbackUrl = planet.successCallbackUrl
            failureCallbackUrl = planet.failureCallbackUrl
            additionalProperties = planet.additionalProperties.toMutableMap()
        }

        fun id(id: Long) = id(JsonField.of(id))

        /**
         * Sets [Builder.id] to an arbitrary JSON value.
         *
         * You should usually call [Builder.id] with a well-typed [Long] value instead. This method
         * is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun id(id: JsonField<Long>) = apply { this.id = id }

        fun name(name: String) = name(JsonField.of(name))

        /**
         * Sets [Builder.name] to an arbitrary JSON value.
         *
         * You should usually call [Builder.name] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun name(name: JsonField<String>) = apply { this.name = name }

        fun description(description: String?) = description(JsonField.ofNullable(description))

        /**
         * Sets [Builder.description] to an arbitrary JSON value.
         *
         * You should usually call [Builder.description] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun description(description: JsonField<String>) = apply { this.description = description }

        fun type(type: Type) = type(JsonField.of(type))

        /**
         * Sets [Builder.type] to an arbitrary JSON value.
         *
         * You should usually call [Builder.type] with a well-typed [Type] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun type(type: JsonField<Type>) = apply { this.type = type }

        /** A score from 0 to 1 indicating potential habitability */
        fun habitabilityIndex(habitabilityIndex: Float) =
            habitabilityIndex(JsonField.of(habitabilityIndex))

        /**
         * Sets [Builder.habitabilityIndex] to an arbitrary JSON value.
         *
         * You should usually call [Builder.habitabilityIndex] with a well-typed [Float] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun habitabilityIndex(habitabilityIndex: JsonField<Float>) = apply {
            this.habitabilityIndex = habitabilityIndex
        }

        fun physicalProperties(physicalProperties: PhysicalProperties) =
            physicalProperties(JsonField.of(physicalProperties))

        /**
         * Sets [Builder.physicalProperties] to an arbitrary JSON value.
         *
         * You should usually call [Builder.physicalProperties] with a well-typed
         * [PhysicalProperties] value instead. This method is primarily for setting the field to an
         * undocumented or not yet supported value.
         */
        fun physicalProperties(physicalProperties: JsonField<PhysicalProperties>) = apply {
            this.physicalProperties = physicalProperties
        }

        /** Atmospheric composition */
        fun atmosphere(atmosphere: List<Atmosphere>) = atmosphere(JsonField.of(atmosphere))

        /**
         * Sets [Builder.atmosphere] to an arbitrary JSON value.
         *
         * You should usually call [Builder.atmosphere] with a well-typed `List<Atmosphere>` value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun atmosphere(atmosphere: JsonField<List<Atmosphere>>) = apply {
            this.atmosphere = atmosphere.map { it.toMutableList() }
        }

        /**
         * Adds a single [Atmosphere] to [Builder.atmosphere].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addAtmosphere(atmosphere: Atmosphere) = apply {
            this.atmosphere =
                (this.atmosphere ?: JsonField.of(mutableListOf())).also {
                    checkKnown("atmosphere", it).add(atmosphere)
                }
        }

        fun discoveredAt(discoveredAt: OffsetDateTime) = discoveredAt(JsonField.of(discoveredAt))

        /**
         * Sets [Builder.discoveredAt] to an arbitrary JSON value.
         *
         * You should usually call [Builder.discoveredAt] with a well-typed [OffsetDateTime] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun discoveredAt(discoveredAt: JsonField<OffsetDateTime>) = apply {
            this.discoveredAt = discoveredAt
        }

        fun image(image: String?) = image(JsonField.ofNullable(image))

        /**
         * Sets [Builder.image] to an arbitrary JSON value.
         *
         * You should usually call [Builder.image] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun image(image: JsonField<String>) = apply { this.image = image }

        fun satellites(satellites: List<Satellite>) = satellites(JsonField.of(satellites))

        /**
         * Sets [Builder.satellites] to an arbitrary JSON value.
         *
         * You should usually call [Builder.satellites] with a well-typed `List<Satellite>` value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun satellites(satellites: JsonField<List<Satellite>>) = apply {
            this.satellites = satellites.map { it.toMutableList() }
        }

        /**
         * Adds a single [Satellite] to [satellites].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addSatellite(satellite: Satellite) = apply {
            satellites =
                (satellites ?: JsonField.of(mutableListOf())).also {
                    checkKnown("satellites", it).add(satellite)
                }
        }

        /** A user */
        fun creator(creator: User) = creator(JsonField.of(creator))

        /**
         * Sets [Builder.creator] to an arbitrary JSON value.
         *
         * You should usually call [Builder.creator] with a well-typed [User] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun creator(creator: JsonField<User>) = apply { this.creator = creator }

        fun tags(tags: List<String>) = tags(JsonField.of(tags))

        /**
         * Sets [Builder.tags] to an arbitrary JSON value.
         *
         * You should usually call [Builder.tags] with a well-typed `List<String>` value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun tags(tags: JsonField<List<String>>) = apply {
            this.tags = tags.map { it.toMutableList() }
        }

        /**
         * Adds a single [String] to [tags].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addTag(tag: String) = apply {
            tags = (tags ?: JsonField.of(mutableListOf())).also { checkKnown("tags", it).add(tag) }
        }

        fun lastUpdated(lastUpdated: OffsetDateTime) = lastUpdated(JsonField.of(lastUpdated))

        /**
         * Sets [Builder.lastUpdated] to an arbitrary JSON value.
         *
         * You should usually call [Builder.lastUpdated] with a well-typed [OffsetDateTime] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun lastUpdated(lastUpdated: JsonField<OffsetDateTime>) = apply {
            this.lastUpdated = lastUpdated
        }

        /** URL which gets invoked upon a successful operation */
        fun successCallbackUrl(successCallbackUrl: String) =
            successCallbackUrl(JsonField.of(successCallbackUrl))

        /**
         * Sets [Builder.successCallbackUrl] to an arbitrary JSON value.
         *
         * You should usually call [Builder.successCallbackUrl] with a well-typed [String] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun successCallbackUrl(successCallbackUrl: JsonField<String>) = apply {
            this.successCallbackUrl = successCallbackUrl
        }

        /** URL which gets invoked upon a failed operation */
        fun failureCallbackUrl(failureCallbackUrl: String) =
            failureCallbackUrl(JsonField.of(failureCallbackUrl))

        /**
         * Sets [Builder.failureCallbackUrl] to an arbitrary JSON value.
         *
         * You should usually call [Builder.failureCallbackUrl] with a well-typed [String] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun failureCallbackUrl(failureCallbackUrl: JsonField<String>) = apply {
            this.failureCallbackUrl = failureCallbackUrl
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [Planet].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .name()
         * .type()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): Planet =
            Planet(
                id,
                checkRequired("name", name),
                description,
                checkRequired("type", type),
                habitabilityIndex,
                physicalProperties,
                (atmosphere ?: JsonMissing.of()).map { it.toImmutable() },
                discoveredAt,
                image,
                (satellites ?: JsonMissing.of()).map { it.toImmutable() },
                creator,
                (tags ?: JsonMissing.of()).map { it.toImmutable() },
                lastUpdated,
                successCallbackUrl,
                failureCallbackUrl,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
     *   match its expected type.
     */
    fun validate(): Planet = apply {
        if (validated) {
            return@apply
        }

        id()
        name()
        description()
        type().validate()
        habitabilityIndex()
        physicalProperties()?.validate()
        atmosphere()?.forEach { it.validate() }
        discoveredAt()
        image()
        satellites()?.forEach { it.validate() }
        creator()?.validate()
        tags()
        lastUpdated()
        successCallbackUrl()
        failureCallbackUrl()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DemoApiScalarGalaxyInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (if (id.asKnown() == null) 0 else 1) +
            (if (name.asKnown() == null) 0 else 1) +
            (if (description.asKnown() == null) 0 else 1) +
            (type.asKnown()?.validity() ?: 0) +
            (if (habitabilityIndex.asKnown() == null) 0 else 1) +
            (physicalProperties.asKnown()?.validity() ?: 0) +
            (atmosphere.asKnown()?.sumOf { it.validity().toInt() } ?: 0) +
            (if (discoveredAt.asKnown() == null) 0 else 1) +
            (if (image.asKnown() == null) 0 else 1) +
            (satellites.asKnown()?.sumOf { it.validity().toInt() } ?: 0) +
            (creator.asKnown()?.validity() ?: 0) +
            (tags.asKnown()?.size ?: 0) +
            (if (lastUpdated.asKnown() == null) 0 else 1) +
            (if (successCallbackUrl.asKnown() == null) 0 else 1) +
            (if (failureCallbackUrl.asKnown() == null) 0 else 1)

    class Type @JsonCreator private constructor(private val value: JsonField<String>) : Enum {

        /**
         * Returns this class instance's raw value.
         *
         * This is usually only useful if this instance was deserialized from data that doesn't
         * match any known member, and you want to know that value. For example, if the SDK is on an
         * older version than the API, then the API may respond with new members that the SDK is
         * unaware of.
         */
        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            val PLANET = of("planet")

            val TERRESTRIAL = of("terrestrial")

            val GAS_GIANT = of("gas_giant")

            val ICE_GIANT = of("ice_giant")

            val DWARF = of("dwarf")

            val SUPER_EARTH = of("super_earth")

            fun of(value: String) = Type(JsonField.of(value))
        }

        /** An enum containing [Type]'s known values. */
        enum class Known {
            PLANET,
            TERRESTRIAL,
            GAS_GIANT,
            ICE_GIANT,
            DWARF,
            SUPER_EARTH,
        }

        /**
         * An enum containing [Type]'s known values, as well as an [_UNKNOWN] member.
         *
         * An instance of [Type] can contain an unknown value in a couple of cases:
         * - It was deserialized from data that doesn't match any known member. For example, if the
         *   SDK is on an older version than the API, then the API may respond with new members that
         *   the SDK is unaware of.
         * - It was constructed with an arbitrary value using the [of] method.
         */
        enum class Value {
            PLANET,
            TERRESTRIAL,
            GAS_GIANT,
            ICE_GIANT,
            DWARF,
            SUPER_EARTH,
            /** An enum member indicating that [Type] was instantiated with an unknown value. */
            _UNKNOWN,
        }

        /**
         * Returns an enum member corresponding to this class instance's value, or [Value._UNKNOWN]
         * if the class was instantiated with an unknown value.
         *
         * Use the [known] method instead if you're certain the value is always known or if you want
         * to throw for the unknown case.
         */
        fun value(): Value =
            when (this) {
                PLANET -> Value.PLANET
                TERRESTRIAL -> Value.TERRESTRIAL
                GAS_GIANT -> Value.GAS_GIANT
                ICE_GIANT -> Value.ICE_GIANT
                DWARF -> Value.DWARF
                SUPER_EARTH -> Value.SUPER_EARTH
                else -> Value._UNKNOWN
            }

        /**
         * Returns an enum member corresponding to this class instance's value.
         *
         * Use the [value] method instead if you're uncertain the value is always known and don't
         * want to throw for the unknown case.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if this class instance's value is a not a
         *   known member.
         */
        fun known(): Known =
            when (this) {
                PLANET -> Known.PLANET
                TERRESTRIAL -> Known.TERRESTRIAL
                GAS_GIANT -> Known.GAS_GIANT
                ICE_GIANT -> Known.ICE_GIANT
                DWARF -> Known.DWARF
                SUPER_EARTH -> Known.SUPER_EARTH
                else -> throw DemoApiScalarGalaxyInvalidDataException("Unknown Type: $value")
            }

        /**
         * Returns this class instance's primitive wire representation.
         *
         * This differs from the [toString] method because that method is primarily for debugging
         * and generally doesn't throw.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if this class instance's value does not
         *   have the expected primitive type.
         */
        fun asString(): String =
            _value().asString()
                ?: throw DemoApiScalarGalaxyInvalidDataException("Value is not a String")

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
         *   match its expected type.
         */
        fun validate(): Type = apply {
            if (validated) {
                return@apply
            }

            known()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int = if (value() == Value._UNKNOWN) 0 else 1

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Type && value == other.value
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }

    class PhysicalProperties
    @JsonCreator(mode = JsonCreator.Mode.DISABLED)
    private constructor(
        private val mass: JsonField<Float>,
        private val radius: JsonField<Float>,
        private val gravity: JsonField<Float>,
        private val temperature: JsonField<Temperature>,
        private val additionalProperties: MutableMap<String, JsonValue>,
    ) {

        @JsonCreator
        private constructor(
            @JsonProperty("mass") @ExcludeMissing mass: JsonField<Float> = JsonMissing.of(),
            @JsonProperty("radius") @ExcludeMissing radius: JsonField<Float> = JsonMissing.of(),
            @JsonProperty("gravity") @ExcludeMissing gravity: JsonField<Float> = JsonMissing.of(),
            @JsonProperty("temperature")
            @ExcludeMissing
            temperature: JsonField<Temperature> = JsonMissing.of(),
        ) : this(mass, radius, gravity, temperature, mutableMapOf())

        /**
         * Mass in Earth masses (must be greater than 0)
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun mass(): Float? = mass.getNullable("mass")

        /**
         * Radius in Earth radii (must be greater than 0)
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun radius(): Float? = radius.getNullable("radius")

        /**
         * Surface gravity in Earth g
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun gravity(): Float? = gravity.getNullable("gravity")

        /**
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun temperature(): Temperature? = temperature.getNullable("temperature")

        /**
         * Returns the raw JSON value of [mass].
         *
         * Unlike [mass], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("mass") @ExcludeMissing fun _mass(): JsonField<Float> = mass

        /**
         * Returns the raw JSON value of [radius].
         *
         * Unlike [radius], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("radius") @ExcludeMissing fun _radius(): JsonField<Float> = radius

        /**
         * Returns the raw JSON value of [gravity].
         *
         * Unlike [gravity], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("gravity") @ExcludeMissing fun _gravity(): JsonField<Float> = gravity

        /**
         * Returns the raw JSON value of [temperature].
         *
         * Unlike [temperature], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("temperature")
        @ExcludeMissing
        fun _temperature(): JsonField<Temperature> = temperature

        @JsonAnySetter
        private fun putAdditionalProperty(key: String, value: JsonValue) {
            additionalProperties.put(key, value)
        }

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> =
            Collections.unmodifiableMap(additionalProperties)

        fun toBuilder() = Builder().from(this)

        companion object {

            /** Returns a mutable builder for constructing an instance of [PhysicalProperties]. */
            fun builder() = Builder()
        }

        /** A builder for [PhysicalProperties]. */
        class Builder internal constructor() {

            private var mass: JsonField<Float> = JsonMissing.of()
            private var radius: JsonField<Float> = JsonMissing.of()
            private var gravity: JsonField<Float> = JsonMissing.of()
            private var temperature: JsonField<Temperature> = JsonMissing.of()
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            internal fun from(physicalProperties: PhysicalProperties) = apply {
                mass = physicalProperties.mass
                radius = physicalProperties.radius
                gravity = physicalProperties.gravity
                temperature = physicalProperties.temperature
                additionalProperties = physicalProperties.additionalProperties.toMutableMap()
            }

            /** Mass in Earth masses (must be greater than 0) */
            fun mass(mass: Float) = mass(JsonField.of(mass))

            /**
             * Sets [Builder.mass] to an arbitrary JSON value.
             *
             * You should usually call [Builder.mass] with a well-typed [Float] value instead. This
             * method is primarily for setting the field to an undocumented or not yet supported
             * value.
             */
            fun mass(mass: JsonField<Float>) = apply { this.mass = mass }

            /** Radius in Earth radii (must be greater than 0) */
            fun radius(radius: Float) = radius(JsonField.of(radius))

            /**
             * Sets [Builder.radius] to an arbitrary JSON value.
             *
             * You should usually call [Builder.radius] with a well-typed [Float] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun radius(radius: JsonField<Float>) = apply { this.radius = radius }

            /** Surface gravity in Earth g */
            fun gravity(gravity: Float) = gravity(JsonField.of(gravity))

            /**
             * Sets [Builder.gravity] to an arbitrary JSON value.
             *
             * You should usually call [Builder.gravity] with a well-typed [Float] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun gravity(gravity: JsonField<Float>) = apply { this.gravity = gravity }

            fun temperature(temperature: Temperature) = temperature(JsonField.of(temperature))

            /**
             * Sets [Builder.temperature] to an arbitrary JSON value.
             *
             * You should usually call [Builder.temperature] with a well-typed [Temperature] value
             * instead. This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun temperature(temperature: JsonField<Temperature>) = apply {
                this.temperature = temperature
            }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                putAllAdditionalProperties(additionalProperties)
            }

            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

            fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                keys.forEach(::removeAdditionalProperty)
            }

            /**
             * Returns an immutable instance of [PhysicalProperties].
             *
             * Further updates to this [Builder] will not mutate the returned instance.
             */
            fun build(): PhysicalProperties =
                PhysicalProperties(
                    mass,
                    radius,
                    gravity,
                    temperature,
                    additionalProperties.toMutableMap(),
                )
        }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
         *   match its expected type.
         */
        fun validate(): PhysicalProperties = apply {
            if (validated) {
                return@apply
            }

            mass()
            radius()
            gravity()
            temperature()?.validate()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            (if (mass.asKnown() == null) 0 else 1) +
                (if (radius.asKnown() == null) 0 else 1) +
                (if (gravity.asKnown() == null) 0 else 1) +
                (temperature.asKnown()?.validity() ?: 0)

        class Temperature
        @JsonCreator(mode = JsonCreator.Mode.DISABLED)
        private constructor(
            private val min: JsonField<Float>,
            private val max: JsonField<Float>,
            private val average: JsonField<Float>,
            private val additionalProperties: MutableMap<String, JsonValue>,
        ) {

            @JsonCreator
            private constructor(
                @JsonProperty("min") @ExcludeMissing min: JsonField<Float> = JsonMissing.of(),
                @JsonProperty("max") @ExcludeMissing max: JsonField<Float> = JsonMissing.of(),
                @JsonProperty("average")
                @ExcludeMissing
                average: JsonField<Float> = JsonMissing.of(),
            ) : this(min, max, average, mutableMapOf())

            /**
             * Minimum temperature in Kelvin
             *
             * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected
             *   type (e.g. if the server responded with an unexpected value).
             */
            fun min(): Float? = min.getNullable("min")

            /**
             * Maximum temperature in Kelvin
             *
             * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected
             *   type (e.g. if the server responded with an unexpected value).
             */
            fun max(): Float? = max.getNullable("max")

            /**
             * Average temperature in Kelvin
             *
             * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected
             *   type (e.g. if the server responded with an unexpected value).
             */
            fun average(): Float? = average.getNullable("average")

            /**
             * Returns the raw JSON value of [min].
             *
             * Unlike [min], this method doesn't throw if the JSON field has an unexpected type.
             */
            @JsonProperty("min") @ExcludeMissing fun _min(): JsonField<Float> = min

            /**
             * Returns the raw JSON value of [max].
             *
             * Unlike [max], this method doesn't throw if the JSON field has an unexpected type.
             */
            @JsonProperty("max") @ExcludeMissing fun _max(): JsonField<Float> = max

            /**
             * Returns the raw JSON value of [average].
             *
             * Unlike [average], this method doesn't throw if the JSON field has an unexpected type.
             */
            @JsonProperty("average") @ExcludeMissing fun _average(): JsonField<Float> = average

            @JsonAnySetter
            private fun putAdditionalProperty(key: String, value: JsonValue) {
                additionalProperties.put(key, value)
            }

            @JsonAnyGetter
            @ExcludeMissing
            fun _additionalProperties(): Map<String, JsonValue> =
                Collections.unmodifiableMap(additionalProperties)

            fun toBuilder() = Builder().from(this)

            companion object {

                /** Returns a mutable builder for constructing an instance of [Temperature]. */
                fun builder() = Builder()
            }

            /** A builder for [Temperature]. */
            class Builder internal constructor() {

                private var min: JsonField<Float> = JsonMissing.of()
                private var max: JsonField<Float> = JsonMissing.of()
                private var average: JsonField<Float> = JsonMissing.of()
                private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

                internal fun from(temperature: Temperature) = apply {
                    min = temperature.min
                    max = temperature.max
                    average = temperature.average
                    additionalProperties = temperature.additionalProperties.toMutableMap()
                }

                /** Minimum temperature in Kelvin */
                fun min(min: Float) = min(JsonField.of(min))

                /**
                 * Sets [Builder.min] to an arbitrary JSON value.
                 *
                 * You should usually call [Builder.min] with a well-typed [Float] value instead.
                 * This method is primarily for setting the field to an undocumented or not yet
                 * supported value.
                 */
                fun min(min: JsonField<Float>) = apply { this.min = min }

                /** Maximum temperature in Kelvin */
                fun max(max: Float) = max(JsonField.of(max))

                /**
                 * Sets [Builder.max] to an arbitrary JSON value.
                 *
                 * You should usually call [Builder.max] with a well-typed [Float] value instead.
                 * This method is primarily for setting the field to an undocumented or not yet
                 * supported value.
                 */
                fun max(max: JsonField<Float>) = apply { this.max = max }

                /** Average temperature in Kelvin */
                fun average(average: Float) = average(JsonField.of(average))

                /**
                 * Sets [Builder.average] to an arbitrary JSON value.
                 *
                 * You should usually call [Builder.average] with a well-typed [Float] value
                 * instead. This method is primarily for setting the field to an undocumented or not
                 * yet supported value.
                 */
                fun average(average: JsonField<Float>) = apply { this.average = average }

                fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                    this.additionalProperties.clear()
                    putAllAdditionalProperties(additionalProperties)
                }

                fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                    additionalProperties.put(key, value)
                }

                fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) =
                    apply {
                        this.additionalProperties.putAll(additionalProperties)
                    }

                fun removeAdditionalProperty(key: String) = apply {
                    additionalProperties.remove(key)
                }

                fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                    keys.forEach(::removeAdditionalProperty)
                }

                /**
                 * Returns an immutable instance of [Temperature].
                 *
                 * Further updates to this [Builder] will not mutate the returned instance.
                 */
                fun build(): Temperature =
                    Temperature(min, max, average, additionalProperties.toMutableMap())
            }

            private var validated: Boolean = false

            /**
             * Validates that the types of all values in this object match their expected types
             * recursively.
             *
             * This method is _not_ forwards compatible with new types from the API for existing
             * fields.
             *
             * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object
             *   doesn't match its expected type.
             */
            fun validate(): Temperature = apply {
                if (validated) {
                    return@apply
                }

                min()
                max()
                average()
                validated = true
            }

            fun isValid(): Boolean =
                try {
                    validate()
                    true
                } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                    false
                }

            /**
             * Returns a score indicating how many valid values are contained in this object
             * recursively.
             *
             * Used for best match union deserialization.
             */
            internal fun validity(): Int =
                (if (min.asKnown() == null) 0 else 1) +
                    (if (max.asKnown() == null) 0 else 1) +
                    (if (average.asKnown() == null) 0 else 1)

            override fun equals(other: Any?): Boolean {
                if (this === other) {
                    return true
                }

                return other is Temperature &&
                    min == other.min &&
                    max == other.max &&
                    average == other.average &&
                    additionalProperties == other.additionalProperties
            }

            private val hashCode: Int by lazy {
                Objects.hash(min, max, average, additionalProperties)
            }

            override fun hashCode(): Int = hashCode

            override fun toString() =
                "Temperature{min=$min, max=$max, average=$average, additionalProperties=$additionalProperties}"
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is PhysicalProperties &&
                mass == other.mass &&
                radius == other.radius &&
                gravity == other.gravity &&
                temperature == other.temperature &&
                additionalProperties == other.additionalProperties
        }

        private val hashCode: Int by lazy {
            Objects.hash(mass, radius, gravity, temperature, additionalProperties)
        }

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "PhysicalProperties{mass=$mass, radius=$radius, gravity=$gravity, temperature=$temperature, additionalProperties=$additionalProperties}"
    }

    /** Atmospheric composition */
    class Atmosphere
    @JsonCreator(mode = JsonCreator.Mode.DISABLED)
    private constructor(
        private val compound: JsonField<String>,
        private val percentage: JsonField<Float>,
        private val additionalProperties: MutableMap<String, JsonValue>,
    ) {

        @JsonCreator
        private constructor(
            @JsonProperty("compound")
            @ExcludeMissing
            compound: JsonField<String> = JsonMissing.of(),
            @JsonProperty("percentage")
            @ExcludeMissing
            percentage: JsonField<Float> = JsonMissing.of(),
        ) : this(compound, percentage, mutableMapOf())

        /**
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun compound(): String? = compound.getNullable("compound")

        /**
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun percentage(): Float? = percentage.getNullable("percentage")

        /**
         * Returns the raw JSON value of [compound].
         *
         * Unlike [compound], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("compound") @ExcludeMissing fun _compound(): JsonField<String> = compound

        /**
         * Returns the raw JSON value of [percentage].
         *
         * Unlike [percentage], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("percentage") @ExcludeMissing fun _percentage(): JsonField<Float> = percentage

        @JsonAnySetter
        private fun putAdditionalProperty(key: String, value: JsonValue) {
            additionalProperties.put(key, value)
        }

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> =
            Collections.unmodifiableMap(additionalProperties)

        fun toBuilder() = Builder().from(this)

        companion object {

            /** Returns a mutable builder for constructing an instance of [Atmosphere]. */
            fun builder() = Builder()
        }

        /** A builder for [Atmosphere]. */
        class Builder internal constructor() {

            private var compound: JsonField<String> = JsonMissing.of()
            private var percentage: JsonField<Float> = JsonMissing.of()
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            internal fun from(atmosphere: Atmosphere) = apply {
                compound = atmosphere.compound
                percentage = atmosphere.percentage
                additionalProperties = atmosphere.additionalProperties.toMutableMap()
            }

            fun compound(compound: String) = compound(JsonField.of(compound))

            /**
             * Sets [Builder.compound] to an arbitrary JSON value.
             *
             * You should usually call [Builder.compound] with a well-typed [String] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun compound(compound: JsonField<String>) = apply { this.compound = compound }

            fun percentage(percentage: Float) = percentage(JsonField.of(percentage))

            /**
             * Sets [Builder.percentage] to an arbitrary JSON value.
             *
             * You should usually call [Builder.percentage] with a well-typed [Float] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun percentage(percentage: JsonField<Float>) = apply { this.percentage = percentage }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                putAllAdditionalProperties(additionalProperties)
            }

            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

            fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                keys.forEach(::removeAdditionalProperty)
            }

            /**
             * Returns an immutable instance of [Atmosphere].
             *
             * Further updates to this [Builder] will not mutate the returned instance.
             */
            fun build(): Atmosphere =
                Atmosphere(compound, percentage, additionalProperties.toMutableMap())
        }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
         *   match its expected type.
         */
        fun validate(): Atmosphere = apply {
            if (validated) {
                return@apply
            }

            compound()
            percentage()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            (if (compound.asKnown() == null) 0 else 1) +
                (if (percentage.asKnown() == null) 0 else 1)

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Atmosphere &&
                compound == other.compound &&
                percentage == other.percentage &&
                additionalProperties == other.additionalProperties
        }

        private val hashCode: Int by lazy {
            Objects.hash(compound, percentage, additionalProperties)
        }

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "Atmosphere{compound=$compound, percentage=$percentage, additionalProperties=$additionalProperties}"
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is Planet &&
            id == other.id &&
            name == other.name &&
            description == other.description &&
            type == other.type &&
            habitabilityIndex == other.habitabilityIndex &&
            physicalProperties == other.physicalProperties &&
            atmosphere == other.atmosphere &&
            discoveredAt == other.discoveredAt &&
            image == other.image &&
            satellites == other.satellites &&
            creator == other.creator &&
            tags == other.tags &&
            lastUpdated == other.lastUpdated &&
            successCallbackUrl == other.successCallbackUrl &&
            failureCallbackUrl == other.failureCallbackUrl &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            id,
            name,
            description,
            type,
            habitabilityIndex,
            physicalProperties,
            atmosphere,
            discoveredAt,
            image,
            satellites,
            creator,
            tags,
            lastUpdated,
            successCallbackUrl,
            failureCallbackUrl,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "Planet{id=$id, name=$name, description=$description, type=$type, habitabilityIndex=$habitabilityIndex, physicalProperties=$physicalProperties, atmosphere=$atmosphere, discoveredAt=$discoveredAt, image=$image, satellites=$satellites, creator=$creator, tags=$tags, lastUpdated=$lastUpdated, successCallbackUrl=$successCallbackUrl, failureCallbackUrl=$failureCallbackUrl, additionalProperties=$additionalProperties}"
}
