// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.planets

import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.Params
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.core.http.Headers
import com.demoapiscalargalaxy.api.core.http.QueryParams
import java.util.Objects

/** Sometimes you make mistakes, that's fine. No worries, you can update all planets. */
class PlanetUpdateParams
private constructor(
    private val planetId: Long?,
    private val planet: Planet,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
) : Params {

    fun planetId(): Long? = planetId

    /** A planet in the Scalar Galaxy */
    fun planet(): Planet = planet

    fun _additionalBodyProperties(): Map<String, JsonValue> = planet._additionalProperties()

    /** Additional headers to send with the request. */
    fun _additionalHeaders(): Headers = additionalHeaders

    /** Additional query param to send with the request. */
    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [PlanetUpdateParams].
         *
         * The following fields are required:
         * ```kotlin
         * .planet()
         * ```
         */
        fun builder() = Builder()
    }

    /** A builder for [PlanetUpdateParams]. */
    class Builder internal constructor() {

        private var planetId: Long? = null
        private var planet: Planet? = null
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()

        internal fun from(planetUpdateParams: PlanetUpdateParams) = apply {
            planetId = planetUpdateParams.planetId
            planet = planetUpdateParams.planet
            additionalHeaders = planetUpdateParams.additionalHeaders.toBuilder()
            additionalQueryParams = planetUpdateParams.additionalQueryParams.toBuilder()
        }

        fun planetId(planetId: Long?) = apply { this.planetId = planetId }

        /**
         * Alias for [Builder.planetId].
         *
         * This unboxed primitive overload exists for backwards compatibility.
         */
        fun planetId(planetId: Long) = planetId(planetId as Long?)

        /** A planet in the Scalar Galaxy */
        fun planet(planet: Planet) = apply { this.planet = planet }

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        /**
         * Returns an immutable instance of [PlanetUpdateParams].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .planet()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): PlanetUpdateParams =
            PlanetUpdateParams(
                planetId,
                checkRequired("planet", planet),
                additionalHeaders.build(),
                additionalQueryParams.build(),
            )
    }

    fun _body(): Planet = planet

    fun _pathParam(index: Int): String =
        when (index) {
            0 -> planetId?.toString() ?: ""
            else -> ""
        }

    override fun _headers(): Headers = additionalHeaders

    override fun _queryParams(): QueryParams = additionalQueryParams

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is PlanetUpdateParams &&
            planetId == other.planetId &&
            planet == other.planet &&
            additionalHeaders == other.additionalHeaders &&
            additionalQueryParams == other.additionalQueryParams
    }

    override fun hashCode(): Int =
        Objects.hash(planetId, planet, additionalHeaders, additionalQueryParams)

    override fun toString() =
        "PlanetUpdateParams{planetId=$planetId, planet=$planet, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams}"
}
