// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.planets

import com.demoapiscalargalaxy.api.core.ExcludeMissing
import com.demoapiscalargalaxy.api.core.JsonField
import com.demoapiscalargalaxy.api.core.JsonMissing
import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.checkKnown
import com.demoapiscalargalaxy.api.core.toImmutable
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Collections
import java.util.Objects

class PlanetListResponse
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val meta: JsonField<PaginatedResource.Meta>,
    private val data: JsonField<List<Planet>>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("meta")
        @ExcludeMissing
        meta: JsonField<PaginatedResource.Meta> = JsonMissing.of(),
        @JsonProperty("data") @ExcludeMissing data: JsonField<List<Planet>> = JsonMissing.of(),
    ) : this(meta, data, mutableMapOf())

    fun toPaginatedResource(): PaginatedResource = PaginatedResource.builder().meta(meta).build()

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun meta(): PaginatedResource.Meta? = meta.getNullable("meta")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun data(): List<Planet>? = data.getNullable("data")

    /**
     * Returns the raw JSON value of [meta].
     *
     * Unlike [meta], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("meta") @ExcludeMissing fun _meta(): JsonField<PaginatedResource.Meta> = meta

    /**
     * Returns the raw JSON value of [data].
     *
     * Unlike [data], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("data") @ExcludeMissing fun _data(): JsonField<List<Planet>> = data

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /** Returns a mutable builder for constructing an instance of [PlanetListResponse]. */
        fun builder() = Builder()
    }

    /** A builder for [PlanetListResponse]. */
    class Builder internal constructor() {

        private var meta: JsonField<PaginatedResource.Meta> = JsonMissing.of()
        private var data: JsonField<MutableList<Planet>>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(planetListResponse: PlanetListResponse) = apply {
            meta = planetListResponse.meta
            data = planetListResponse.data.map { it.toMutableList() }
            additionalProperties = planetListResponse.additionalProperties.toMutableMap()
        }

        fun meta(meta: PaginatedResource.Meta) = meta(JsonField.of(meta))

        /**
         * Sets [Builder.meta] to an arbitrary JSON value.
         *
         * You should usually call [Builder.meta] with a well-typed [PaginatedResource.Meta] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun meta(meta: JsonField<PaginatedResource.Meta>) = apply { this.meta = meta }

        fun data(data: List<Planet>) = data(JsonField.of(data))

        /**
         * Sets [Builder.data] to an arbitrary JSON value.
         *
         * You should usually call [Builder.data] with a well-typed `List<Planet>` value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun data(data: JsonField<List<Planet>>) = apply {
            this.data = data.map { it.toMutableList() }
        }

        /**
         * Adds a single [Planet] to [Builder.data].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addData(data: Planet) = apply {
            this.data =
                (this.data ?: JsonField.of(mutableListOf())).also {
                    checkKnown("data", it).add(data)
                }
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [PlanetListResponse].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): PlanetListResponse =
            PlanetListResponse(
                meta,
                (data ?: JsonMissing.of()).map { it.toImmutable() },
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
     *   match its expected type.
     */
    fun validate(): PlanetListResponse = apply {
        if (validated) {
            return@apply
        }

        meta()?.validate()
        data()?.forEach { it.validate() }
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DemoApiScalarGalaxyInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (meta.asKnown()?.validity() ?: 0) + (data.asKnown()?.sumOf { it.validity().toInt() } ?: 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is PlanetListResponse &&
            meta == other.meta &&
            data == other.data &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy { Objects.hash(meta, data, additionalProperties) }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "PlanetListResponse{meta=$meta, data=$data, additionalProperties=$additionalProperties}"
}
