// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.planets

import com.demoapiscalargalaxy.api.core.ExcludeMissing
import com.demoapiscalargalaxy.api.core.JsonField
import com.demoapiscalargalaxy.api.core.JsonMissing
import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime
import java.util.Collections
import java.util.Objects

class PlanetUploadImageResponse
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val message: JsonField<String>,
    private val imageUrl: JsonField<String>,
    private val uploadedAt: JsonField<OffsetDateTime>,
    private val fileSize: JsonField<Long>,
    private val mimeType: JsonField<String>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("message") @ExcludeMissing message: JsonField<String> = JsonMissing.of(),
        @JsonProperty("imageUrl") @ExcludeMissing imageUrl: JsonField<String> = JsonMissing.of(),
        @JsonProperty("uploadedAt")
        @ExcludeMissing
        uploadedAt: JsonField<OffsetDateTime> = JsonMissing.of(),
        @JsonProperty("fileSize") @ExcludeMissing fileSize: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("mimeType") @ExcludeMissing mimeType: JsonField<String> = JsonMissing.of(),
    ) : this(message, imageUrl, uploadedAt, fileSize, mimeType, mutableMapOf())

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun message(): String? = message.getNullable("message")

    /**
     * The URL where the uploaded image can be accessed
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun imageUrl(): String? = imageUrl.getNullable("imageUrl")

    /**
     * Timestamp when the image was uploaded
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun uploadedAt(): OffsetDateTime? = uploadedAt.getNullable("uploadedAt")

    /**
     * Size of the uploaded image in bytes
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun fileSize(): Long? = fileSize.getNullable("fileSize")

    /**
     * The content type of the uploaded image
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun mimeType(): String? = mimeType.getNullable("mimeType")

    /**
     * Returns the raw JSON value of [message].
     *
     * Unlike [message], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("message") @ExcludeMissing fun _message(): JsonField<String> = message

    /**
     * Returns the raw JSON value of [imageUrl].
     *
     * Unlike [imageUrl], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("imageUrl") @ExcludeMissing fun _imageUrl(): JsonField<String> = imageUrl

    /**
     * Returns the raw JSON value of [uploadedAt].
     *
     * Unlike [uploadedAt], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("uploadedAt")
    @ExcludeMissing
    fun _uploadedAt(): JsonField<OffsetDateTime> = uploadedAt

    /**
     * Returns the raw JSON value of [fileSize].
     *
     * Unlike [fileSize], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("fileSize") @ExcludeMissing fun _fileSize(): JsonField<Long> = fileSize

    /**
     * Returns the raw JSON value of [mimeType].
     *
     * Unlike [mimeType], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("mimeType") @ExcludeMissing fun _mimeType(): JsonField<String> = mimeType

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [PlanetUploadImageResponse].
         */
        fun builder() = Builder()
    }

    /** A builder for [PlanetUploadImageResponse]. */
    class Builder internal constructor() {

        private var message: JsonField<String> = JsonMissing.of()
        private var imageUrl: JsonField<String> = JsonMissing.of()
        private var uploadedAt: JsonField<OffsetDateTime> = JsonMissing.of()
        private var fileSize: JsonField<Long> = JsonMissing.of()
        private var mimeType: JsonField<String> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(planetUploadImageResponse: PlanetUploadImageResponse) = apply {
            message = planetUploadImageResponse.message
            imageUrl = planetUploadImageResponse.imageUrl
            uploadedAt = planetUploadImageResponse.uploadedAt
            fileSize = planetUploadImageResponse.fileSize
            mimeType = planetUploadImageResponse.mimeType
            additionalProperties = planetUploadImageResponse.additionalProperties.toMutableMap()
        }

        fun message(message: String) = message(JsonField.of(message))

        /**
         * Sets [Builder.message] to an arbitrary JSON value.
         *
         * You should usually call [Builder.message] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun message(message: JsonField<String>) = apply { this.message = message }

        /** The URL where the uploaded image can be accessed */
        fun imageUrl(imageUrl: String) = imageUrl(JsonField.of(imageUrl))

        /**
         * Sets [Builder.imageUrl] to an arbitrary JSON value.
         *
         * You should usually call [Builder.imageUrl] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun imageUrl(imageUrl: JsonField<String>) = apply { this.imageUrl = imageUrl }

        /** Timestamp when the image was uploaded */
        fun uploadedAt(uploadedAt: OffsetDateTime) = uploadedAt(JsonField.of(uploadedAt))

        /**
         * Sets [Builder.uploadedAt] to an arbitrary JSON value.
         *
         * You should usually call [Builder.uploadedAt] with a well-typed [OffsetDateTime] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun uploadedAt(uploadedAt: JsonField<OffsetDateTime>) = apply {
            this.uploadedAt = uploadedAt
        }

        /** Size of the uploaded image in bytes */
        fun fileSize(fileSize: Long) = fileSize(JsonField.of(fileSize))

        /**
         * Sets [Builder.fileSize] to an arbitrary JSON value.
         *
         * You should usually call [Builder.fileSize] with a well-typed [Long] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun fileSize(fileSize: JsonField<Long>) = apply { this.fileSize = fileSize }

        /** The content type of the uploaded image */
        fun mimeType(mimeType: String) = mimeType(JsonField.of(mimeType))

        /**
         * Sets [Builder.mimeType] to an arbitrary JSON value.
         *
         * You should usually call [Builder.mimeType] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun mimeType(mimeType: JsonField<String>) = apply { this.mimeType = mimeType }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [PlanetUploadImageResponse].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): PlanetUploadImageResponse =
            PlanetUploadImageResponse(
                message,
                imageUrl,
                uploadedAt,
                fileSize,
                mimeType,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
     *   match its expected type.
     */
    fun validate(): PlanetUploadImageResponse = apply {
        if (validated) {
            return@apply
        }

        message()
        imageUrl()
        uploadedAt()
        fileSize()
        mimeType()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DemoApiScalarGalaxyInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (if (message.asKnown() == null) 0 else 1) +
            (if (imageUrl.asKnown() == null) 0 else 1) +
            (if (uploadedAt.asKnown() == null) 0 else 1) +
            (if (fileSize.asKnown() == null) 0 else 1) +
            (if (mimeType.asKnown() == null) 0 else 1)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is PlanetUploadImageResponse &&
            message == other.message &&
            imageUrl == other.imageUrl &&
            uploadedAt == other.uploadedAt &&
            fileSize == other.fileSize &&
            mimeType == other.mimeType &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(message, imageUrl, uploadedAt, fileSize, mimeType, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "PlanetUploadImageResponse{message=$message, imageUrl=$imageUrl, uploadedAt=$uploadedAt, fileSize=$fileSize, mimeType=$mimeType, additionalProperties=$additionalProperties}"
}
