// File generated by Scalar SDK Generator. DO NOT EDIT.

package com.demoapiscalargalaxy.api.models.planets

import com.demoapiscalargalaxy.api.core.Enum
import com.demoapiscalargalaxy.api.core.ExcludeMissing
import com.demoapiscalargalaxy.api.core.JsonField
import com.demoapiscalargalaxy.api.core.JsonMissing
import com.demoapiscalargalaxy.api.core.JsonValue
import com.demoapiscalargalaxy.api.core.checkRequired
import com.demoapiscalargalaxy.api.errors.DemoApiScalarGalaxyInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Collections
import java.util.Objects

/** Every satellite in the Scalar Galaxy */
class Satellite
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val id: JsonField<Long>,
    private val name: JsonField<String>,
    private val description: JsonField<String>,
    private val diameter: JsonField<Float>,
    private val type: JsonField<Type>,
    private val orbit: JsonField<Orbit>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("id") @ExcludeMissing id: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("name") @ExcludeMissing name: JsonField<String> = JsonMissing.of(),
        @JsonProperty("description")
        @ExcludeMissing
        description: JsonField<String> = JsonMissing.of(),
        @JsonProperty("diameter") @ExcludeMissing diameter: JsonField<Float> = JsonMissing.of(),
        @JsonProperty("type") @ExcludeMissing type: JsonField<Type> = JsonMissing.of(),
        @JsonProperty("orbit") @ExcludeMissing orbit: JsonField<Orbit> = JsonMissing.of(),
    ) : this(id, name, description, diameter, type, orbit, mutableMapOf())

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun id(): Long? = id.getNullable("id")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type or
     *   is unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun name(): String = name.getRequired("name")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun description(): String? = description.getNullable("description")

    /**
     * Diameter in kilometers
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun diameter(): Float? = diameter.getNullable("diameter")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type or
     *   is unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun type(): Type = type.getRequired("type")

    /**
     * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
     *   (e.g. if the server responded with an unexpected value).
     */
    fun orbit(): Orbit? = orbit.getNullable("orbit")

    /**
     * Returns the raw JSON value of [id].
     *
     * Unlike [id], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("id") @ExcludeMissing fun _id(): JsonField<Long> = id

    /**
     * Returns the raw JSON value of [name].
     *
     * Unlike [name], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("name") @ExcludeMissing fun _name(): JsonField<String> = name

    /**
     * Returns the raw JSON value of [description].
     *
     * Unlike [description], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("description") @ExcludeMissing fun _description(): JsonField<String> = description

    /**
     * Returns the raw JSON value of [diameter].
     *
     * Unlike [diameter], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("diameter") @ExcludeMissing fun _diameter(): JsonField<Float> = diameter

    /**
     * Returns the raw JSON value of [type].
     *
     * Unlike [type], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("type") @ExcludeMissing fun _type(): JsonField<Type> = type

    /**
     * Returns the raw JSON value of [orbit].
     *
     * Unlike [orbit], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("orbit") @ExcludeMissing fun _orbit(): JsonField<Orbit> = orbit

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [Satellite].
         *
         * The following fields are required:
         * ```kotlin
         * .name()
         * .type()
         * ```
         */
        fun builder() = Builder()
    }

    /** A builder for [Satellite]. */
    class Builder internal constructor() {

        private var id: JsonField<Long> = JsonMissing.of()
        private var name: JsonField<String>? = null
        private var description: JsonField<String> = JsonMissing.of()
        private var diameter: JsonField<Float> = JsonMissing.of()
        private var type: JsonField<Type>? = null
        private var orbit: JsonField<Orbit> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(satellite: Satellite) = apply {
            id = satellite.id
            name = satellite.name
            description = satellite.description
            diameter = satellite.diameter
            type = satellite.type
            orbit = satellite.orbit
            additionalProperties = satellite.additionalProperties.toMutableMap()
        }

        fun id(id: Long) = id(JsonField.of(id))

        /**
         * Sets [Builder.id] to an arbitrary JSON value.
         *
         * You should usually call [Builder.id] with a well-typed [Long] value instead. This method
         * is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun id(id: JsonField<Long>) = apply { this.id = id }

        fun name(name: String) = name(JsonField.of(name))

        /**
         * Sets [Builder.name] to an arbitrary JSON value.
         *
         * You should usually call [Builder.name] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun name(name: JsonField<String>) = apply { this.name = name }

        fun description(description: String?) = description(JsonField.ofNullable(description))

        /**
         * Sets [Builder.description] to an arbitrary JSON value.
         *
         * You should usually call [Builder.description] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun description(description: JsonField<String>) = apply { this.description = description }

        /** Diameter in kilometers */
        fun diameter(diameter: Float) = diameter(JsonField.of(diameter))

        /**
         * Sets [Builder.diameter] to an arbitrary JSON value.
         *
         * You should usually call [Builder.diameter] with a well-typed [Float] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun diameter(diameter: JsonField<Float>) = apply { this.diameter = diameter }

        fun type(type: Type) = type(JsonField.of(type))

        /**
         * Sets [Builder.type] to an arbitrary JSON value.
         *
         * You should usually call [Builder.type] with a well-typed [Type] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun type(type: JsonField<Type>) = apply { this.type = type }

        fun orbit(orbit: Orbit) = orbit(JsonField.of(orbit))

        /**
         * Sets [Builder.orbit] to an arbitrary JSON value.
         *
         * You should usually call [Builder.orbit] with a well-typed [Orbit] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun orbit(orbit: JsonField<Orbit>) = apply { this.orbit = orbit }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [Satellite].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .name()
         * .type()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): Satellite =
            Satellite(
                id,
                checkRequired("name", name),
                description,
                diameter,
                checkRequired("type", type),
                orbit,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
     *   match its expected type.
     */
    fun validate(): Satellite = apply {
        if (validated) {
            return@apply
        }

        id()
        name()
        description()
        diameter()
        type().validate()
        orbit()?.validate()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DemoApiScalarGalaxyInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (if (id.asKnown() == null) 0 else 1) +
            (if (name.asKnown() == null) 0 else 1) +
            (if (description.asKnown() == null) 0 else 1) +
            (if (diameter.asKnown() == null) 0 else 1) +
            (type.asKnown()?.validity() ?: 0) +
            (orbit.asKnown()?.validity() ?: 0)

    class Type @JsonCreator private constructor(private val value: JsonField<String>) : Enum {

        /**
         * Returns this class instance's raw value.
         *
         * This is usually only useful if this instance was deserialized from data that doesn't
         * match any known member, and you want to know that value. For example, if the SDK is on an
         * older version than the API, then the API may respond with new members that the SDK is
         * unaware of.
         */
        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            val SATELLITE = of("satellite")

            val MOON = of("moon")

            val ASTEROID = of("asteroid")

            val COMET = of("comet")

            fun of(value: String) = Type(JsonField.of(value))
        }

        /** An enum containing [Type]'s known values. */
        enum class Known {
            SATELLITE,
            MOON,
            ASTEROID,
            COMET,
        }

        /**
         * An enum containing [Type]'s known values, as well as an [_UNKNOWN] member.
         *
         * An instance of [Type] can contain an unknown value in a couple of cases:
         * - It was deserialized from data that doesn't match any known member. For example, if the
         *   SDK is on an older version than the API, then the API may respond with new members that
         *   the SDK is unaware of.
         * - It was constructed with an arbitrary value using the [of] method.
         */
        enum class Value {
            SATELLITE,
            MOON,
            ASTEROID,
            COMET,
            /** An enum member indicating that [Type] was instantiated with an unknown value. */
            _UNKNOWN,
        }

        /**
         * Returns an enum member corresponding to this class instance's value, or [Value._UNKNOWN]
         * if the class was instantiated with an unknown value.
         *
         * Use the [known] method instead if you're certain the value is always known or if you want
         * to throw for the unknown case.
         */
        fun value(): Value =
            when (this) {
                SATELLITE -> Value.SATELLITE
                MOON -> Value.MOON
                ASTEROID -> Value.ASTEROID
                COMET -> Value.COMET
                else -> Value._UNKNOWN
            }

        /**
         * Returns an enum member corresponding to this class instance's value.
         *
         * Use the [value] method instead if you're uncertain the value is always known and don't
         * want to throw for the unknown case.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if this class instance's value is a not a
         *   known member.
         */
        fun known(): Known =
            when (this) {
                SATELLITE -> Known.SATELLITE
                MOON -> Known.MOON
                ASTEROID -> Known.ASTEROID
                COMET -> Known.COMET
                else -> throw DemoApiScalarGalaxyInvalidDataException("Unknown Type: $value")
            }

        /**
         * Returns this class instance's primitive wire representation.
         *
         * This differs from the [toString] method because that method is primarily for debugging
         * and generally doesn't throw.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if this class instance's value does not
         *   have the expected primitive type.
         */
        fun asString(): String =
            _value().asString()
                ?: throw DemoApiScalarGalaxyInvalidDataException("Value is not a String")

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
         *   match its expected type.
         */
        fun validate(): Type = apply {
            if (validated) {
                return@apply
            }

            known()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int = if (value() == Value._UNKNOWN) 0 else 1

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Type && value == other.value
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }

    class Orbit
    @JsonCreator(mode = JsonCreator.Mode.DISABLED)
    private constructor(
        private val planetId: JsonField<Long>,
        private val orbitalPeriod: JsonField<Float>,
        private val distance: JsonField<Float>,
        private val additionalProperties: MutableMap<String, JsonValue>,
    ) {

        @JsonCreator
        private constructor(
            @JsonProperty("planetId") @ExcludeMissing planetId: JsonField<Long> = JsonMissing.of(),
            @JsonProperty("orbitalPeriod")
            @ExcludeMissing
            orbitalPeriod: JsonField<Float> = JsonMissing.of(),
            @JsonProperty("distance") @ExcludeMissing distance: JsonField<Float> = JsonMissing.of(),
        ) : this(planetId, orbitalPeriod, distance, mutableMapOf())

        /**
         * The ID of the planet this satellite orbits
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun planetId(): Long? = planetId.getNullable("planetId")

        /**
         * Orbital period in Earth days
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun orbitalPeriod(): Float? = orbitalPeriod.getNullable("orbitalPeriod")

        /**
         * Average distance from the planet in kilometers
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if the JSON field has an unexpected type
         *   (e.g. if the server responded with an unexpected value).
         */
        fun distance(): Float? = distance.getNullable("distance")

        /**
         * Returns the raw JSON value of [planetId].
         *
         * Unlike [planetId], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("planetId") @ExcludeMissing fun _planetId(): JsonField<Long> = planetId

        /**
         * Returns the raw JSON value of [orbitalPeriod].
         *
         * Unlike [orbitalPeriod], this method doesn't throw if the JSON field has an unexpected
         * type.
         */
        @JsonProperty("orbitalPeriod")
        @ExcludeMissing
        fun _orbitalPeriod(): JsonField<Float> = orbitalPeriod

        /**
         * Returns the raw JSON value of [distance].
         *
         * Unlike [distance], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("distance") @ExcludeMissing fun _distance(): JsonField<Float> = distance

        @JsonAnySetter
        private fun putAdditionalProperty(key: String, value: JsonValue) {
            additionalProperties.put(key, value)
        }

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> =
            Collections.unmodifiableMap(additionalProperties)

        fun toBuilder() = Builder().from(this)

        companion object {

            /** Returns a mutable builder for constructing an instance of [Orbit]. */
            fun builder() = Builder()
        }

        /** A builder for [Orbit]. */
        class Builder internal constructor() {

            private var planetId: JsonField<Long> = JsonMissing.of()
            private var orbitalPeriod: JsonField<Float> = JsonMissing.of()
            private var distance: JsonField<Float> = JsonMissing.of()
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            internal fun from(orbit: Orbit) = apply {
                planetId = orbit.planetId
                orbitalPeriod = orbit.orbitalPeriod
                distance = orbit.distance
                additionalProperties = orbit.additionalProperties.toMutableMap()
            }

            /** The ID of the planet this satellite orbits */
            fun planetId(planetId: Long) = planetId(JsonField.of(planetId))

            /**
             * Sets [Builder.planetId] to an arbitrary JSON value.
             *
             * You should usually call [Builder.planetId] with a well-typed [Long] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun planetId(planetId: JsonField<Long>) = apply { this.planetId = planetId }

            /** Orbital period in Earth days */
            fun orbitalPeriod(orbitalPeriod: Float) = orbitalPeriod(JsonField.of(orbitalPeriod))

            /**
             * Sets [Builder.orbitalPeriod] to an arbitrary JSON value.
             *
             * You should usually call [Builder.orbitalPeriod] with a well-typed [Float] value
             * instead. This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun orbitalPeriod(orbitalPeriod: JsonField<Float>) = apply {
                this.orbitalPeriod = orbitalPeriod
            }

            /** Average distance from the planet in kilometers */
            fun distance(distance: Float) = distance(JsonField.of(distance))

            /**
             * Sets [Builder.distance] to an arbitrary JSON value.
             *
             * You should usually call [Builder.distance] with a well-typed [Float] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun distance(distance: JsonField<Float>) = apply { this.distance = distance }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                putAllAdditionalProperties(additionalProperties)
            }

            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

            fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                keys.forEach(::removeAdditionalProperty)
            }

            /**
             * Returns an immutable instance of [Orbit].
             *
             * Further updates to this [Builder] will not mutate the returned instance.
             */
            fun build(): Orbit =
                Orbit(planetId, orbitalPeriod, distance, additionalProperties.toMutableMap())
        }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DemoApiScalarGalaxyInvalidDataException if any value type in this object doesn't
         *   match its expected type.
         */
        fun validate(): Orbit = apply {
            if (validated) {
                return@apply
            }

            planetId()
            orbitalPeriod()
            distance()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DemoApiScalarGalaxyInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            (if (planetId.asKnown() == null) 0 else 1) +
                (if (orbitalPeriod.asKnown() == null) 0 else 1) +
                (if (distance.asKnown() == null) 0 else 1)

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Orbit &&
                planetId == other.planetId &&
                orbitalPeriod == other.orbitalPeriod &&
                distance == other.distance &&
                additionalProperties == other.additionalProperties
        }

        private val hashCode: Int by lazy {
            Objects.hash(planetId, orbitalPeriod, distance, additionalProperties)
        }

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "Orbit{planetId=$planetId, orbitalPeriod=$orbitalPeriod, distance=$distance, additionalProperties=$additionalProperties}"
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is Satellite &&
            id == other.id &&
            name == other.name &&
            description == other.description &&
            diameter == other.diameter &&
            type == other.type &&
            orbit == other.orbit &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(id, name, description, diameter, type, orbit, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "Satellite{id=$id, name=$name, description=$description, diameter=$diameter, type=$type, orbit=$orbit, additionalProperties=$additionalProperties}"
}
